"""
Evidence report markdown generator.

Pure function — no DB, no I/O, no external dependencies.
Called from job_handler.py after EvidenceLeadAgent.run() completes.
"""

from __future__ import annotations

import datetime
from .models import CriterionResult, EvidenceReference, EvidenceReport

_OVERALL_ICON = {
    "ALL_MET": "✅",
    "PARTIALLY_MET": "⚠️",
    "NOT_MET": "❌",
    "INCONCLUSIVE": "❓",
}

_CRITERION_ICON = {
    "MET": "✅",
    "PARTIALLY_MET": "⚠️",
    "NOT_MET": "❌",
    "INSUFFICIENT_EVIDENCE": "❓",
}


def generate_markdown_report(
    report: EvidenceReport,
    task_title: str | None = None,
    task_description: str | None = None,
) -> str:
    """
    Generate a rich markdown evidence report from a completed EvidenceReport.

    Args:
        report:           Fully-populated EvidenceReport (all criteria attached).
        task_title:       Human-readable task title. Falls back to task_id if omitted.
        task_description: Optional task description for context.

    Returns:
        Markdown string ready to store as markdown_report TEXT in the DB.
    """
    lines: list[str] = []
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    title = task_title or f"Task {report.task_id}"

    overall_icon = _OVERALL_ICON.get(report.overall_verdict, "❓")
    overall_label = report.overall_verdict.replace("_", " ").title()

    # ── Cover ─────────────────────────────────────────────────────────────────
    lines.append("# AI Evidence Check Report")
    lines.append("")
    lines.append(f"> **Task:** {title}")
    if task_description:
        lines.append(f"> **Description:** {task_description}")
    lines.append(f"> **Generated:** {now}")
    lines.append(f"> **Overall Verdict:** {overall_icon} {overall_label}")
    lines.append(f"> **Report Job:** `{report.job_id}`")
    lines.append("")

    # ── Executive Summary ─────────────────────────────────────────────────────
    met = sum(1 for r in report.criteria_results if r.verdict == "MET")
    partially = sum(1 for r in report.criteria_results if r.verdict == "PARTIALLY_MET")
    not_met = sum(1 for r in report.criteria_results if r.verdict == "NOT_MET")
    insufficient = sum(1 for r in report.criteria_results if r.verdict == "INSUFFICIENT_EVIDENCE")
    total = len(report.criteria_results)

    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Overall Verdict | {overall_icon} **{overall_label}** |")
    lines.append(f"| Criteria Evaluated | {total} |")
    lines.append(f"| ✅ Met | {met} |")
    lines.append(f"| ⚠️ Partially Met | {partially} |")
    lines.append(f"| ❌ Not Met | {not_met} |")
    lines.append(f"| ❓ Insufficient Evidence | {insufficient} |")
    lines.append(f"| Attachments Analyzed | {report.attachment_count} |")
    lines.append(f"| Pages Scanned | {report.total_pages_analyzed} |")
    if report.tokens_consumed:
        lines.append(f"| Tokens Consumed | {report.tokens_consumed:,} |")
    if report.duration_seconds:
        lines.append(f"| Evaluation Duration | {report.duration_seconds:.1f}s |")
    lines.append("")

    # ── Gap Analysis Summary ──────────────────────────────────────────────────
    gaps = [(cr, cr.gap_analysis) for cr in report.criteria_results if cr.gap_analysis]
    if gaps:
        lines.append("## Gap Analysis")
        lines.append("")
        lines.append(
            "The following criteria have identified evidence gaps. "
            "Addressing these gaps will move the verdict toward **Met**."
        )
        lines.append("")
        for cr, gap in gaps:
            icon = _CRITERION_ICON.get(cr.verdict, "❓")
            verdict_label = cr.verdict.replace("_", " ").title()
            lines.append(f"**{icon} {cr.criterion_text}** _{verdict_label}_")
            lines.append("")
            lines.append(f"> {gap}")
            lines.append("")

    # ── Criteria Evaluation ───────────────────────────────────────────────────
    if report.criteria_results:
        lines.append("---")
        lines.append("")
        lines.append("## Criteria Evaluation")
        lines.append("")

        for i, cr in enumerate(report.criteria_results, start=1):
            _render_criterion(lines, i, cr)

    # ── Methodology note ─────────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("## Methodology")
    lines.append("")
    lines.append(
        "This report was generated by a 4-stage multi-agentic RAG pipeline:"
    )
    lines.append("")
    lines.append(
        "1. **HyDE Query Expansion** — Hypothetical Document Embeddings generate "
        "positive and negative queries to maximise semantic recall from the vector store."
    )
    lines.append(
        "2. **Semantic Retrieval + Full Corpus Map** — Qdrant vector search across all "
        "indexed document chunks, combined with a parallel batch scan of the entire corpus."
    )
    lines.append(
        "3. **Re-Ranking** — An LLM re-ranks and deduplicates all candidate references by "
        "relevance to the acceptance criterion."
    )
    lines.append(
        "4. **Synthesis** — A final LLM pass produces a grounded verdict with explicit "
        "citations from the re-ranked evidence."
    )
    lines.append("")
    lines.append(
        "> ⚠️ AI-generated analysis. Always review cited excerpts in the original documents "
        "before relying on this report for audit or compliance decisions."
    )
    lines.append("")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by K-Control AI Evidence Checker · {now}*")
    if report.langfuse_trace_id:
        lines.append(f"*Trace ID: `{report.langfuse_trace_id}`*")
    lines.append("")

    return "\n".join(lines)


def _render_criterion(lines: list[str], index: int, cr: CriterionResult) -> None:
    icon = _CRITERION_ICON.get(cr.verdict, "❓")
    verdict_label = cr.verdict.replace("_", " ").title()

    lines.append(f"### {index}. {icon} {cr.criterion_text}")
    lines.append("")
    lines.append(f"**Verdict:** {verdict_label}")
    if cr.threshold_met is not None:
        lines.append(f"**Threshold Met:** {'Yes' if cr.threshold_met else 'No'}")
    lines.append("")
    lines.append("**Justification:**")
    lines.append("")
    # Wrap in blockquote
    for para in cr.justification.split("\n"):
        lines.append(f"> {para}" if para.strip() else ">")
    lines.append("")

    if cr.gap_analysis:
        lines.append("**Gap Analysis** _(what evidence is missing)_:")
        lines.append("")
        lines.append(f"> 🔍 {cr.gap_analysis}")
        lines.append("")

    if cr.evidence_references:
        lines.append(f"#### Supporting Evidence ({len(cr.evidence_references)} reference{'s' if len(cr.evidence_references) != 1 else ''})")
        lines.append("")
        lines.append("| Document | Page | Section | Confidence | Excerpt |")
        lines.append("|---|---|---|---|---|")
        for ref in cr.evidence_references:
            _render_ref_row(lines, ref)
        lines.append("")

    if cr.conflicting_references:
        lines.append(f"#### ⚠️ Conflicting Evidence ({len(cr.conflicting_references)} reference{'s' if len(cr.conflicting_references) != 1 else ''})")
        lines.append("")
        lines.append("| Document | Page | Section | Confidence | Excerpt |")
        lines.append("|---|---|---|---|---|")
        for ref in cr.conflicting_references:
            _render_ref_row(lines, ref)
        lines.append("")


def _render_ref_row(lines: list[str], ref: EvidenceReference) -> None:
    page = str(ref.page_number) if ref.page_number is not None else "—"
    section = ref.section_or_sheet or "—"
    confidence = f"{int(ref.confidence * 100)}%"
    # Escape pipe chars in excerpt so the table doesn't break
    excerpt = ref.excerpt[:150].replace("|", "\\|").replace("\n", " ")
    lines.append(f"| `{ref.document_filename}` | {page} | {section} | {confidence} | {excerpt} |")
