"""FastAPI router for the attachments API.

Static sub-paths (/upload, /bulk-upload, /counts, /health) are declared
BEFORE parameterised routes (/{attachment_id}/...) to prevent FastAPI from
interpreting a literal path segment as a UUID parameter.

File bytes are never returned by the API.  Clients receive presigned URLs
generated by the configured object storage provider and download directly.
"""

from __future__ import annotations

import asyncio
from importlib import import_module
from typing import Annotated

from fastapi import Depends, Form, Query, Request, UploadFile, status

from .dependencies import get_attachment_service
from .schemas import (
    AttachmentListResponse,
    AttachmentResponse,
    BulkUploadResponse,
    DownloadHistoryResponse,
    GdprDeleteResponse,
    PresignedDownloadResponse,
    StorageHealthResponse,
    StorageUsageResponse,
    UpdateAttachmentRequest,
    UploadAttachmentResponse,
)
from .service import AttachmentService

_telemetry_module = import_module("backend.01_core.telemetry")
_auth_deps_module = import_module("backend.03_auth_manage.dependencies")
_errors_module = import_module("backend.01_core.errors")
_perm_check_module = import_module("backend.03_auth_manage._permission_check")
_access_scope_module = import_module("backend.07_tasks.access_scope")
_engagement_repo_module = import_module("backend.12_engagements.repository")
_engagement_service_module = import_module("backend.12_engagements.service")
_grc_access_module = import_module("backend.03_auth_manage.18_grc_roles.access_check")

InstrumentedAPIRouter = _telemetry_module.InstrumentedAPIRouter
get_current_access_claims = _auth_deps_module.get_current_access_claims
AuthorizationError = _errors_module.AuthorizationError
ValidationError = _errors_module.ValidationError
require_permission = _perm_check_module.require_permission
is_assignee_portal_mode = _access_scope_module.is_assignee_portal_mode
EngagementRepository = _engagement_repo_module.EngagementRepository
EngagementService = _engagement_service_module.EngagementService
check_engagement_access = _grc_access_module.check_engagement_access

router = InstrumentedAPIRouter(tags=["attachments"])

# Feature flag: "attachments" flag (seeded in 20260322_seed-comments-attachments-permissions.sql).
# Platform-level enforcement is done via permission checks (attachments.view / attachments.create).
# Org-level toggle: set org setting "feature_attachments_enabled=false" to disable per org.

_MAX_BULK_FILES = 10

_logging_module = import_module("backend.01_core.logging_utils")
_router_logger = _logging_module.get_logger("backend.attachments.router")


def _get_engagement_service() -> EngagementService:
    return EngagementService(EngagementRepository())


async def _get_user_email(conn, user_id: str, *, is_api_key: bool) -> str | None:
    if is_api_key:
        return "admin@test.com"
    return await conn.fetchval(
        'SELECT property_value FROM "03_auth_manage"."05_dtl_user_properties" WHERE user_id = $1::uuid AND property_key = \'email\'',
        user_id,
    )


async def _resolve_engagement_attachment_scope(conn, engagement_id: str, claims) -> tuple[str, bool, str | None]:
    service = _get_engagement_service()
    if not await service.is_user_globally_active(conn, user_id=claims.subject):
        raise AuthorizationError("User account is inactive or suspended.")

    owner_eng = await service.get_engagement(conn, engagement_id, claims.tenant_key)
    if owner_eng:
        try:
            await require_permission(conn, claims.subject, "attachments.view")
            has_access = await check_engagement_access(
                conn,
                user_id=claims.subject,
                org_id=owner_eng.org_id,
                engagement_id=engagement_id,
            )
            if has_access:
                return claims.tenant_key, False, None
        except AuthorizationError:
            pass

    membership_access = await service.get_active_membership_access(
        conn,
        engagement_id=engagement_id,
        user_id=claims.subject,
    )
    if membership_access:
        return str(membership_access["tenant_key"]), True, str(membership_access["membership_id"])

    user_email = await _get_user_email(conn, claims.subject, is_api_key=claims.is_api_key)
    if user_email:
        guest_tenant = await service.validate_auditor_access_and_get_tenant(conn, engagement_id, user_email)
        if guest_tenant:
            return guest_tenant, True, None

    raise AuthorizationError("You do not have access to this engagement evidence.")


async def _assert_attachment_engagement_boundary(conn, service: AttachmentService, attachment_id: str, claims) -> None:
    record = await service._repository.get_attachment_by_id(conn, attachment_id)
    if record is None:
        raise ValidationError("Attachment not found.")
    engagement_service = _get_engagement_service()
    if not await engagement_service.is_user_globally_active(conn, user_id=claims.subject):
        raise AuthorizationError("User account is inactive or suspended.")

    contexts = await service._repository.list_attachment_engagement_contexts(conn, attachment_id)
    if not contexts:
        return

    user_email = await _get_user_email(conn, claims.subject, is_api_key=claims.is_api_key)

    for context in contexts:
        engagement_id = context["engagement_id"]

        owner_eng = await engagement_service.get_engagement(conn, engagement_id, claims.tenant_key)
        if owner_eng:
            try:
                await require_permission(conn, claims.subject, "attachments.view")
                has_access = await check_engagement_access(
                    conn,
                    user_id=claims.subject,
                    org_id=owner_eng.org_id,
                    engagement_id=engagement_id,
                )
                if has_access:
                    return
            except AuthorizationError:
                pass

        membership_access = await engagement_service.get_active_membership_access(
            conn,
            engagement_id=engagement_id,
            user_id=claims.subject,
        )
        if membership_access:
            has_grant = await service._repository.has_active_creator_approved_evidence_grant(
                conn,
                engagement_id=engagement_id,
                membership_id=str(membership_access["membership_id"]),
                attachment_id=attachment_id,
            )
            if has_grant:
                return

    raise AuthorizationError("You do not have access to this attachment.")


async def _trigger_evidence_check_for_task(
    pool,
    tenant_key: str,
    org_id: str | None,
    task_id: str,
    triggered_by_attachment_id: str | None,
    user_id: str,
) -> None:
    """Fire-and-forget: enqueue evidence check after a task attachment upload."""
    try:
        _jh = import_module("backend.20_ai.16_evidence_checker.job_handler")
        # Load current attachment IDs for the task
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT id::text
                FROM "09_attachments"."01_fct_attachments"
                WHERE entity_type = 'task' AND entity_id = $1::uuid AND is_deleted = FALSE
                """,
                task_id,
            )
        attachment_ids = [r["id"] for r in rows]
        if not attachment_ids:
            return
        # enqueue_evidence_check expects a raw asyncpg.Pool
        raw_pool = pool.pool if hasattr(pool, "pool") else pool
        await _jh.enqueue_evidence_check(
            pool=raw_pool,
            tenant_key=tenant_key,
            org_id=org_id or "",
            task_id=task_id,
            triggered_by_attachment_id=triggered_by_attachment_id,
            attachment_ids=attachment_ids,
            user_id=user_id,
        )
    except Exception as exc:
        _router_logger.warning(
            "evidence_check.auto_trigger_failed: %s", exc,
            extra={"task_id": task_id},
        )


def _get_client_ip(request: Request) -> str | None:
    """Extract client IP, respecting trusted proxy headers when configured."""
    forwarded_for = request.headers.get("X-Forwarded-For")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()
    return request.client.host if request.client else None


# ---------------------------------------------------------------------------
# GET /attachments — list attachments for an entity
# ---------------------------------------------------------------------------

@router.get("/attachments", response_model=AttachmentListResponse)
async def list_attachments(
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
    entity_type: str | None = Query(default=None, description="Entity type (task, risk, control, etc.)"),
    entity_id: str | None = Query(default=None, description="UUID of the entity"),
    engagement_id: str | None = Query(default=None, description="Optional: Scope all evidence for an engagement"),
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=50, ge=1, le=200),
) -> AttachmentListResponse:
    """List all non-deleted attachments for a given entity or engagement. Returns metadata only."""
    if not engagement_id and (not entity_type or not entity_id):
        raise ValidationError("Either engagement_id or both entity_type and entity_id must be provided.")

    effective_tenant_key = claims.tenant_key
    auditor_only = False
    viewer_membership_id: str | None = None

    if not is_assignee_portal_mode(claims.portal_mode):
        async with service._database_pool.acquire() as conn:
            if engagement_id:
                effective_tenant_key, auditor_only, viewer_membership_id = await _resolve_engagement_attachment_scope(
                    conn,
                    engagement_id,
                    claims,
                )
            else:
                await require_permission(conn, claims.subject, "attachments.view")
    return await service.list_attachments(
        user_id=claims.subject,
        tenant_key=effective_tenant_key,
        portal_mode=claims.portal_mode,
        entity_type=entity_type,
        entity_id=entity_id,
        engagement_id=engagement_id,
        auditor_only=auditor_only,
        viewer_membership_id=viewer_membership_id,
        page=page,
        per_page=per_page,
    )


# ---------------------------------------------------------------------------
# POST /attachments/upload — upload a single attachment (backward compatible)
# NOTE: must be before /attachments/{id} to prevent routing shadow
# ---------------------------------------------------------------------------

@router.post(
    "/attachments/upload",
    response_model=UploadAttachmentResponse,
    status_code=status.HTTP_201_CREATED,
)
async def upload_attachment(
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
    file: UploadFile = ...,
    entity_type: str = Form(...),
    entity_id: str = Form(...),
    org_id: str | None = Form(default=None),
    workspace_id: str | None = Form(default=None),
    description: str | None = Form(default=None),
) -> UploadAttachmentResponse:
    """Upload a single file attachment to the configured object storage provider.

    - Validates file size against STORAGE_MAX_FILE_SIZE_MB
    - Validates content type against the allowed list
    - Computes SHA-256 checksum for integrity verification
    - Uploads to object storage BEFORE writing to the database
    - On DB failure, automatically removes the uploaded object
    - ``org_id`` and ``workspace_id`` are used to build the hierarchical storage key
    """
    # Verify user has permission to create attachments on this entity
    if not is_assignee_portal_mode(claims.portal_mode):
        async with service._database_pool.acquire() as conn:
            await require_permission(conn, claims.subject, "attachments.create")

    file_data, _checksum = await AttachmentService._read_file_chunked(file)
    original_filename = file.filename or "attachment"
    declared_content_type = file.content_type or "application/octet-stream"

    result = await service.upload_attachment(
        user_id=claims.subject,
        tenant_key=claims.tenant_key,
        portal_mode=claims.portal_mode,
        entity_type=entity_type,
        entity_id=entity_id,
        description=description,
        original_filename=original_filename,
        declared_content_type=declared_content_type,
        file_data=file_data,
        org_id=org_id,
        workspace_id=workspace_id,
    )

    # Auto-trigger evidence check for task attachments (fire and forget)
    if entity_type == "task":
        asyncio.create_task(
            _trigger_evidence_check_for_task(
                pool=service._database_pool,
                tenant_key=claims.tenant_key,
                org_id=org_id,
                task_id=entity_id,
                triggered_by_attachment_id=result.id,
                user_id=claims.subject,
            )
        )

    return result


# ---------------------------------------------------------------------------
# POST /attachments/bulk-upload — upload up to 10 files in one request
# NOTE: must be before /attachments/{id} to prevent routing shadow
# ---------------------------------------------------------------------------

@router.post(
    "/attachments/bulk-upload",
    response_model=BulkUploadResponse,
    status_code=status.HTTP_207_MULTI_STATUS,
)
async def bulk_upload_attachments(
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
    files: list[UploadFile] = ...,
    entity_type: str = Form(...),
    entity_id: str = Form(...),
    org_id: str | None = Form(default=None),
    workspace_id: str | None = Form(default=None),
    description: str | None = Form(default=None),
) -> BulkUploadResponse:
    """Upload up to 10 files in a single request.

    Each file is processed independently — partial success is possible.
    Returns HTTP 207 Multi-Status with per-file results.

    Successful files are in `uploaded`; files that could not be processed are
    in `failed` with a human-readable `error` message.
    """
    # Verify user has permission to create attachments
    if not is_assignee_portal_mode(claims.portal_mode):
        async with service._database_pool.acquire() as conn:
            await require_permission(conn, claims.subject, "attachments.create")

    if len(files) > _MAX_BULK_FILES:
        raise ValidationError(
            f"Too many files. A maximum of {_MAX_BULK_FILES} files may be uploaded at once."
        )

    file_payloads = []
    for upload_file in files:
        file_data, _checksum = await AttachmentService._read_file_chunked(upload_file)
        file_payloads.append({
            "filename": upload_file.filename or "attachment",
            "content_type": upload_file.content_type or "application/octet-stream",
            "data": file_data,
            "description": description,
        })

    result = await service.bulk_upload_attachments(
        user_id=claims.subject,
        tenant_key=claims.tenant_key,
        portal_mode=claims.portal_mode,
        entity_type=entity_type,
        entity_id=entity_id,
        files=file_payloads,
        org_id=org_id,
        workspace_id=workspace_id,
    )

    # Auto-trigger evidence check for task attachments when at least one file succeeded
    if entity_type == "task" and result.total_uploaded > 0:
        first_id = result.uploaded[0].id if result.uploaded else None
        asyncio.create_task(
            _trigger_evidence_check_for_task(
                pool=service._database_pool,
                tenant_key=claims.tenant_key,
                org_id=org_id,
                task_id=entity_id,
                triggered_by_attachment_id=first_id,
                user_id=claims.subject,
            )
        )

    return result


# ---------------------------------------------------------------------------
# GET /attachments/counts — batch attachment counts for multiple entities
# NOTE: must be before /attachments/{id} to prevent routing shadow
# ---------------------------------------------------------------------------

@router.get("/attachments/counts", response_model=dict[str, int])
async def get_attachment_counts(
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
    entity_type: str = Query(..., description="Entity type shared by all entity IDs"),
    entity_ids: list[str] = Query(..., description="Up to 100 entity UUIDs"),
) -> dict[str, int]:
    """Return non-deleted attachment counts for a batch of entity IDs.

    Useful for displaying attachment badges on list pages without N+1 queries.
    Maximum 100 entity IDs per request. Returns a flat {entity_id: count} mapping.
    """
    if not is_assignee_portal_mode(claims.portal_mode):
        async with service._database_pool.acquire() as conn:
            await require_permission(conn, claims.subject, "attachments.view")
    result = await service.get_attachment_counts(
        user_id=claims.subject,
        portal_mode=claims.portal_mode,
        entity_type=entity_type,
        entity_ids=entity_ids,
    )
    return result.counts


# ---------------------------------------------------------------------------
# GET /health — storage provider connectivity check
# NOTE: must be before /attachments/{id} to prevent routing shadow
# ---------------------------------------------------------------------------

@router.get("/health", response_model=StorageHealthResponse)
async def storage_health_check(
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> StorageHealthResponse:
    """Check connectivity to the configured object storage provider.

    Performs a lightweight metadata operation (e.g., HeadBucket for S3) and
    returns timing information.  Requires platform-level admin permission.
    """
    async with service._database_pool.acquire() as conn:
        await require_permission(conn, claims.subject, "admin.view")

    return await service.check_storage_health()


# ---------------------------------------------------------------------------
# GET /attachments/storage-usage — tenant storage usage and quota
# NOTE: must be before /attachments/{id} to prevent routing shadow
# ---------------------------------------------------------------------------

@router.get("/attachments/storage-usage", response_model=StorageUsageResponse)
async def get_storage_usage(
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> StorageUsageResponse:
    """Return current storage usage and quota for the caller's tenant.

    Shows total bytes used, total file count, configured quota, and
    percentage utilisation.  Quota can be customised per-org via the
    ``storage_quota_bytes`` org setting; defaults to 10 GB.
    """
    usage = await service.get_storage_usage(tenant_key=claims.tenant_key)
    return StorageUsageResponse(**usage)


# ---------------------------------------------------------------------------
# DELETE /attachments/admin/users/{user_id}/data — GDPR user data deletion
# NOTE: must be before /attachments/{id} to prevent routing shadow
# ---------------------------------------------------------------------------

@router.delete(
    "/attachments/admin/users/{user_id}/data",
    response_model=GdprDeleteResponse,
)
async def gdpr_delete_user_attachments(
    user_id: str,
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> GdprDeleteResponse:
    """GDPR Article 17 — delete all attachment data for a specific user.

    Soft-deletes all attachments uploaded by the target user within the
    caller's tenant.  Requires ``admin.delete`` permission.
    """
    async with service._database_pool.acquire() as conn:
        await require_permission(conn, claims.subject, "admin.delete")

    result = await service.gdpr_delete_user_data(
        user_id=user_id,
        tenant_key=claims.tenant_key,
        actor_user_id=claims.subject,
    )
    return GdprDeleteResponse(**result)


# ---------------------------------------------------------------------------
# GET /attachments/{id}/download — get presigned download URL
# NOTE: must be before /attachments/{id} to avoid routing collision
# ---------------------------------------------------------------------------

@router.get("/attachments/{attachment_id}/download", response_model=PresignedDownloadResponse)
async def get_download_url(
    attachment_id: str,
    request: Request,
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> PresignedDownloadResponse:
    """Generate a presigned download URL valid for 1 hour.

    Records a download event with client IP and user agent for audit purposes.
    Files are never proxied through the backend — clients download directly
    from object storage using the presigned URL.
    """
    # Verify user has permission to view/download attachments
    async with service._database_pool.acquire() as conn:
        if not is_assignee_portal_mode(claims.portal_mode):
            await require_permission(conn, claims.subject, "attachments.view")
        await _assert_attachment_engagement_boundary(conn, service, attachment_id, claims)

    client_ip = _get_client_ip(request)
    user_agent = request.headers.get("User-Agent")

    return await service.get_download_url(
        user_id=claims.subject,
        attachment_id=attachment_id,
        portal_mode=claims.portal_mode,
        client_ip=client_ip,
        user_agent=user_agent,
    )


# ---------------------------------------------------------------------------
# GET /attachments/{id}/download-history — admin view of download events
# NOTE: must be before /attachments/{id} to avoid routing collision
# ---------------------------------------------------------------------------

@router.get(
    "/attachments/{attachment_id}/download-history",
    response_model=DownloadHistoryResponse,
)
async def get_download_history(
    attachment_id: str,
    request: Request,
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=50, ge=1, le=200),
) -> DownloadHistoryResponse:
    """Retrieve the download history for an attachment. Requires attachments.view permission."""
    async with service._database_pool.acquire() as conn:
        if not is_assignee_portal_mode(claims.portal_mode):
            await require_permission(conn, claims.subject, "attachments.view")
        await _assert_attachment_engagement_boundary(conn, service, attachment_id, claims)

    return await service.get_download_history(
        user_id=claims.subject,
        attachment_id=attachment_id,
        portal_mode=claims.portal_mode,
        page=page,
        per_page=per_page,
    )


# ---------------------------------------------------------------------------
# GET /attachments/{id} — get single attachment metadata
# ---------------------------------------------------------------------------

@router.get("/attachments/{attachment_id}", response_model=AttachmentResponse)
async def get_attachment(
    attachment_id: str,
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> AttachmentResponse:
    """Retrieve attachment metadata. Does not return file content."""
    async with service._database_pool.acquire() as conn:
        if not is_assignee_portal_mode(claims.portal_mode):
            await require_permission(conn, claims.subject, "attachments.view")
        await _assert_attachment_engagement_boundary(conn, service, attachment_id, claims)
    return await service.get_attachment(
        user_id=claims.subject,
        attachment_id=attachment_id,
        portal_mode=claims.portal_mode,
    )


# ---------------------------------------------------------------------------
# PATCH /attachments/{id} — update description only
# ---------------------------------------------------------------------------

@router.patch("/attachments/{attachment_id}", response_model=AttachmentResponse)
async def update_attachment(
    attachment_id: str,
    body: UpdateAttachmentRequest,
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> AttachmentResponse:
    """Update attachment description. Only the description field may be changed post-upload."""
    return await service.update_attachment(
        user_id=claims.subject,
        attachment_id=attachment_id,
        request=body,
        portal_mode=claims.portal_mode,
    )


# ---------------------------------------------------------------------------
# DELETE /attachments/{id} — soft delete + storage removal
# ---------------------------------------------------------------------------

@router.delete("/attachments/{attachment_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_attachment(
    attachment_id: str,
    service: Annotated[AttachmentService, Depends(get_attachment_service)],
    claims=Depends(get_current_access_claims),
) -> None:
    """Soft-delete an attachment and remove it from object storage.

    Only the original uploader or a user with the attachments.delete permission may delete.
    """
    is_uploader = await service.is_uploader(
        user_id=claims.subject, attachment_id=attachment_id
    )
    if not is_uploader:
        async with service._database_pool.acquire() as conn:
            await require_permission(conn, claims.subject, "attachments.delete")

    await service.delete_attachment(
        user_id=claims.subject,
        attachment_id=attachment_id,
        portal_mode=claims.portal_mode,
    )
