"""Pydantic request/response schemas for the attachments API.

Raw file bytes are never returned by the API.  Files are accessed via
time-limited presigned download URLs generated by the object storage provider.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class AttachmentResponse(BaseModel):
    """Full attachment metadata — never contains raw file bytes."""

    id: str
    tenant_key: str
    entity_type: str
    entity_id: str
    uploaded_by: str
    uploader_display_name: str | None = None
    original_filename: str
    storage_provider: str
    storage_bucket: str
    storage_url: str | None = None
    content_type: str
    file_size_bytes: int
    checksum_sha256: str
    virus_scan_status: str
    virus_scan_at: str | None = None
    description: str | None = None
    auditor_access: bool = False
    published_for_audit_by: str | None = None
    published_for_audit_at: str | None = None
    created_at: str
    updated_at: str


class AttachmentListResponse(BaseModel):
    items: list[AttachmentResponse]
    total: int


class UploadAttachmentResponse(BaseModel):
    """Returned immediately after a successful upload."""

    id: str
    tenant_key: str
    entity_type: str
    entity_id: str
    uploaded_by: str
    original_filename: str
    storage_provider: str
    storage_bucket: str
    storage_url: str | None = None
    content_type: str
    file_size_bytes: int
    checksum_sha256: str
    virus_scan_status: str
    description: str | None = None
    created_at: str
    updated_at: str


class BulkUploadResponse(BaseModel):
    """Returned after a multi-file upload request."""

    uploaded: list[UploadAttachmentResponse]
    failed: list[dict]  # {filename: str, error: str}
    total_uploaded: int
    total_failed: int


class UpdateAttachmentRequest(BaseModel):
    """Update attachment metadata (description, auditor visibility)."""

    description: str | None = Field(None, max_length=2000)
    auditor_access: bool | None = None


class PresignedDownloadResponse(BaseModel):
    """Presigned URL response for file download."""

    url: str
    expires_at: str
    filename: str
    attachment_id: str
    content_type: str
    file_size_bytes: int


class DownloadHistoryItem(BaseModel):
    id: str
    attachment_id: str
    downloaded_by: str
    downloaded_at: str
    client_ip: str | None = None
    user_agent: str | None = None


class DownloadHistoryResponse(BaseModel):
    items: list[DownloadHistoryItem]
    total: int


class AttachmentCountsResponse(BaseModel):
    """Mapping of entity_id → attachment count.  Used by list pages for badges."""
    counts: dict[str, int]


class StorageHealthResponse(BaseModel):
    """Storage provider connectivity check result."""
    provider: str
    status: str       # "ok" | "error"
    latency_ms: float | None = None
    error: str | None = None


class StorageUsageResponse(BaseModel):
    """Current storage usage and quota for a tenant."""
    tenant_key: str
    total_bytes: int
    file_count: int
    quota_bytes: int
    usage_percent: float


class GdprDeleteResponse(BaseModel):
    """Result of a GDPR data deletion request."""
    user_id: str
    attachments_deleted: int = 0
    comments_anonymized: int = 0
    reactions_deleted: int = 0
