"""
ReportGenerationAgent — multi-stage pipeline for GRC report generation.

Pipeline stages:
  1. plan      — LLM decides which GRC tools to call
  2. collect   — dispatch tool calls in sequence, aggregate data
  3. analyze   — LLM analyzes collected data → structured JSON insights
  4. write     — LLM writes each section as professional markdown prose
  5. format    — assemble final report with header, TOC, sections, footer

Each stage updates ReportGenState and persists status to DB.
"""

from __future__ import annotations

import json
import time
import datetime
from importlib import import_module
from typing import Any

import asyncpg

from .constants import (
    REPORT_SECTIONS,
    REPORT_TYPE_LABELS,
    ReportStatus,
    ReportType,  # noqa: F401 — used via ReportType.X references in _build_collection_plan
)
from .models import ReportGenState
from .repository import ReportRepository

_logging_module = import_module("backend.01_core.logging_utils")
_dispatcher_mod = import_module("backend.20_ai.05_mcp.dispatcher")
_factory_mod = import_module("backend.20_ai.14_llm_providers.factory")
_pageindex_mod = import_module("backend.20_ai.03_memory.pageindex")
_cache_mod = import_module("backend.01_core.cache")

_logger = _logging_module.get_logger("backend.ai.reports.agent")

MCPToolDispatcher = _dispatcher_mod.MCPToolDispatcher
ToolContext = _dispatcher_mod.ToolContext
get_provider = _factory_mod.get_provider
PageIndexer = _pageindex_mod.PageIndexer
NullPageIndexer = _pageindex_mod.NullPageIndexer
NullCacheManager = _cache_mod.NullCacheManager

_MAX_TOOL_CALLS = 20
_SECTION_MAX_TOKENS = 1200
_ANALYSIS_MAX_TOKENS = 2000


# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

_PLANNER_SYSTEM = """You are a GRC compliance report planner. Given a report type and parameters,
output a JSON plan describing which GRC tool calls to make to collect all data needed.

Report types: executive_summary, compliance_posture, framework_compliance, framework_readiness,
framework_gap_analysis, control_status, risk_summary, board_risk_report, vendor_risk,
remediation_plan, task_health, audit_trail, evidence_report.

Available tools:
- grc_framework_health: {framework_id?, scope_org_id?}
- grc_requirement_gaps: {framework_id, gaps_only?}
- grc_risk_concentration: {framework_id?, top_n?}
- grc_task_health: {}
- grc_control_health: {framework_id?, missing_owner?, missing_tests?, has_overdue_tasks?, min_risk_severity?, limit?}
- grc_list_frameworks: {limit?}
- grc_list_controls: {framework_id?, criticality_code?, search?, limit?}
- grc_list_risks: {level_filter?, status_filter?, limit?}
- grc_list_tasks: {status_filter?, priority_filter?, overdue_only?, limit?}
- grc_get_framework: {framework_id}

Output ONLY valid JSON in this format:
{
  "tool_calls": [
    {"tool": "tool_name", "args": {...}},
    ...
  ]
}

Be comprehensive. Include all tools needed for a thorough report. Max 15 tool calls."""

_ANALYSIS_SYSTEM = """You are a senior GRC analyst. Analyze the collected compliance data and
extract structured insights. Be precise, data-driven, and actionable.

Output ONLY valid JSON with this structure:
{
  "key_metrics": {
    "metric_name": "value or summary"
  },
  "critical_findings": [
    {"finding": "...", "severity": "critical|high|medium", "recommendation": "..."}
  ],
  "trends": ["trend description", ...],
  "strengths": ["area of strength", ...],
  "gaps": [
    {"area": "...", "details": "...", "impact": "..."}
  ],
  "top_risks": [
    {"name": "...", "level": "...", "status": "..."}
  ],
  "compliance_score_estimate": "0-100 with brief rationale",
  "executive_headline": "1-2 sentence executive summary"
}"""

_SECTION_WRITER_SYSTEM = """You are a senior compliance and audit report writer. Write a specific
section of a professional GRC report in Markdown format.

Guidelines:
- Be specific and data-driven — cite actual numbers from the data
- Use tables for structured data (controls, risks, tasks)
- Bold critical figures and key findings
- Use > blockquote for critical alerts: > **⚠ Critical:** description
- Each section should be 200-400 words of substantive content
- Write for a compliance manager or external auditor audience
- Do NOT add a section heading (it will be added automatically)
- Do NOT add "Generated by AI" disclaimers in the section body"""


# ---------------------------------------------------------------------------
# Section-specific prompts
# ---------------------------------------------------------------------------

def _section_prompt(section: str, report_type: str, analysis: dict, raw_data: dict) -> str:
    data_summary = json.dumps(analysis, indent=2, default=str)[:3000]
    raw_snippet = json.dumps(raw_data, indent=2, default=str)[:2000]
    prompts = {
        "executive_summary": f"Write a crisp executive summary section covering: overall compliance posture, top 3 findings, and the single most urgent recommendation. Use the analysis data:\n{data_summary}",
        "executive_overview": f"Write the executive overview. Lead with the compliance score estimate and headline finding. Summarize risk posture. Data:\n{data_summary}",
        "framework_overview": f"Write the framework overview section covering: framework name, category, publisher, version, scope, total controls and requirements. Raw data:\n{raw_snippet}",
        "control_coverage": f"Write the control coverage analysis. Include: total controls, active vs inactive, coverage by category (table), automation potential breakdown. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "risk_exposure": f"Write the risk exposure section. Use a table showing controls with highest risk concentration. Highlight critical and unactioned risks. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "compliance_gaps": f"Write the compliance gaps section. List each gap with impact and remediation path. Use the gaps from analysis. Data:\n{data_summary}",
        "recommendations": f"Write actionable recommendations. Number each one. Order by priority. Be specific — name controls, teams, timeframes. Data:\n{data_summary}",
        "controls_by_category": f"Write the controls by category section. Include a markdown table: Category | Count | Critical | With Tests | Owner Assigned. Raw:\n{raw_snippet}",
        "controls_needing_attention": f"Write the controls needing attention section. List controls missing owners, tests, or with overdue tasks. Use a table. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "test_coverage": f"Write the test coverage section. Show test coverage %, automated vs manual vs semi-automated breakdown, controls without tests. Data:\n{data_summary}",
        "owner_assignment": f"Write the owner assignment section. Show % owned, list unowned critical controls, note which teams own the most. Data:\n{data_summary}",
        "action_items": f"Write the action items section as a prioritized table: Priority | Control | Issue | Recommended Action | Due. Data:\n{data_summary}",
        "risk_landscape": f"Write the risk landscape section. Summarize total risks by level (critical/high/medium/low). Include a severity distribution table. Raw:\n{raw_snippet}",
        "risk_by_category": f"Write risk by category breakdown. Group risks by category/type. Show counts and treatment status per group. Raw:\n{raw_snippet}",
        "treatment_status": f"Write the treatment status section. Show: accepted, mitigating, transferred, closed vs open risks. Note overdue treatment plans. Raw:\n{raw_snippet}",
        "residual_risk": f"Write the residual risk analysis. Identify risks with no treatment plan or unactioned status. Estimate residual exposure. Data:\n{data_summary}",
        "overview": f"Write the task management overview. Show total open, overdue, unassigned counts. State urgency. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "overdue_tasks": f"Write the overdue tasks section. List overdue tasks in a table: Task | Type | Priority | Due Date | Assignee | Days Overdue. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "unassigned_tasks": f"Write the unassigned tasks section. List critical/high unassigned tasks. Note risk of unassigned work. Raw:\n{raw_snippet}",
        "by_priority": f"Write the tasks by priority breakdown. Table: Priority | Total | Overdue | % of Open. Data:\n{data_summary}",
        "by_type": f"Write the tasks by type section. Table: Type | Count | Avg Age (days) | Overdue. Data:\n{data_summary}",
        "resolution_trends": f"Write the resolution trends section. Note resolved this week, average resolution rate. Identify bottlenecks. Data:\n{data_summary}",
        "compliance_score": f"Write the compliance score section. State the score estimate with rationale. Show score components. Data:\n{data_summary}",
        "top_risks": f"Write the top risks section. Table: Risk Name | Level | Treatment | Control Coverage. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "control_health": f"Write the control health section. Overall health score, % with passing tests, % owned, % linked to risks. Data:\n{data_summary}",
        "open_items": f"Write the open items section. Summarize: open tasks, open risks, controls with gaps, pending approvals. Data:\n{data_summary}",
        "key_metrics": f"Write the key metrics dashboard section as a table: Metric | Current | Target | Status. Data:\n{data_summary}",
        "next_steps": f"Write the next steps section. List 5-8 specific actionable next steps with owners and timelines. Data:\n{data_summary}",
        "period_summary": f"Write the audit period summary. State date range, total events, event type breakdown. Raw:\n{raw_snippet}",
        "event_timeline": f"Write the event timeline. Summarize key events chronologically. Raw:\n{raw_snippet}",
        "key_events": f"Write the key events section highlighting significant compliance events. Raw:\n{raw_snippet}",
        "anomalies": f"Write the anomalies section. Flag unusual patterns, access changes, bulk operations. Raw:\n{raw_snippet}",
        "criteria_evaluation": f"Write the criteria evaluation summary. Data:\n{data_summary}",
        "gap_analysis": f"Write the gap analysis. Identify missing evidence and remediation path. Data:\n{data_summary}",
        "methodology": "Write the methodology section describing the AI-driven multi-agent analysis pipeline used to generate this report.",
        # ── Readiness report sections ──────────────────────────────────────────
        "readiness_scorecard": f"Write a readiness scorecard. Show overall readiness % with a breakdown table: Area | Score | Status | Notes. Drive from control coverage, test coverage, owner assignment, and open gaps. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "trust_criteria_coverage": f"Write the trust criteria coverage section. Map controls to framework requirements. Table: Requirement | Controls Mapped | Coverage % | Gap. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "control_gaps": f"Write the control gaps section for a readiness report. List each requirement with missing or insufficient controls. Table: Requirement | Gap Description | Severity | Recommended Action. Data:\n{data_summary}",
        "evidence_status": f"Write the evidence status section. Show which controls have test evidence, which are missing evidence, and coverage %. Table: Control | Tests Defined | Last Test | Status. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "remediation_roadmap": f"Write a prioritized remediation roadmap to achieve readiness. Table: Priority | Item | Effort | Owner | Target Date. Group by critical/high/medium. Data:\n{data_summary}",
        # ── Gap analysis report sections ───────────────────────────────────────
        "annex_a_coverage": f"Write the framework coverage analysis. Map all requirements to implemented controls. Show implemented vs planned vs missing per domain. Table: Domain | Total Requirements | Implemented | Planned | Missing | Coverage %. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "implemented_controls": f"Write the implemented controls section. List controls that are active and have test evidence. Highlight strengths. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "risk_treatment": f"Write the risk treatment section. Show how identified gaps translate to risk exposure. Table: Gap | Related Risks | Risk Level | Treatment Plan. Data:\n{data_summary}",
        "certification_readiness": f"Write the certification readiness assessment. Give a readiness % with rationale. State what remains before certification can be pursued. Data:\n{data_summary}",
        # ── Board risk report sections ─────────────────────────────────────────
        "executive_headline": f"Write a 2-paragraph board-level headline. No jargon. Lead with the single most important risk or finding. State what decision or action is needed from the board. Data:\n{data_summary}",
        "risk_posture_summary": f"Write the risk posture summary for board presentation. Use plain language. Table: Risk Category | Current Exposure | Trend | Board Action Required. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "top_risks_board": f"Write the top risks for board-level consumption. For each: name, business impact, current treatment, and recommended board decision. Limit to top 5. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "compliance_health": f"Write the compliance health section for the board. State % of frameworks in good standing, any regulatory deadlines, and resource adequacy. Data:\n{data_summary}",
        "key_decisions_required": f"Write the key decisions required section. List 3-5 specific decisions the board must make, each with context and recommended option. Data:\n{data_summary}",
        "outlook": f"Write the forward outlook section. Describe the compliance trajectory: improving, stable, or deteriorating — with supporting evidence. Data:\n{data_summary}",
        # ── Remediation plan sections ──────────────────────────────────────────
        "critical_items": f"Write the critical remediation items section. Table: Item | Type (control/risk/task) | Owner | Due Date | Blocking. Only critical priority. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "high_priority_items": f"Write the high priority remediation items. Table: Item | Type | Owner | Due Date | Effort. Data:\n{data_summary}",
        "control_gaps_plan": f"Write the control gaps remediation plan. For each gap: control code, gap description, remediation action, owner, target date. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "risk_remediation": f"Write the risk remediation section. For each open/unactioned critical or high risk: risk name, current status, remediation action, owner. Data:\n{data_summary}",
        "timeline_and_owners": f"Write the timeline and owners section. Build a Gantt-style table: Week/Month | Item | Owner | Status. Group by urgency. Data:\n{data_summary}",
        # ── Compliance posture sections ────────────────────────────────────────
        "framework_coverage_matrix": f"Write the framework coverage matrix. Table: Framework | Total Controls | Active | Coverage % | Open Tasks | Linked Risks | Health. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "cross_framework_gaps": f"Write the cross-framework gaps section. Identify themes that appear as gaps across multiple frameworks — systemic weaknesses. Data:\n{data_summary}",
        "risk_posture_overview": f"Write the risk posture overview. Roll up risk counts across all frameworks. Table: Severity | Count | With Treatment | Unactioned. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "task_backlog_health": f"Write the task backlog health section. Show overdue, unassigned, and critical tasks. Note which frameworks are driving the most overdue work. Data:\n{data_summary}",
        "improvement_recommendations": f"Write the improvement recommendations. Focus on systemic improvements that would benefit multiple frameworks simultaneously. Number each recommendation. Data:\n{data_summary}",
        # ── Vendor / third-party risk sections ────────────────────────────────
        "third_party_risk_overview": f"Write the third-party risk overview. Summarize total vendor-related risks, their concentration, and treatment status. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
        "high_risk_vendors": f"Write the high risk vendors/third parties section. Table: Entity | Risk Level | Controls Covering | Treatment Status | Action Required. Data:\n{data_summary}\nRaw:\n{raw_snippet}",
    }
    return prompts.get(section, f"Write the {section.replace('_', ' ')} section using this data:\n{data_summary}")


# ---------------------------------------------------------------------------
# Data collection plan per report type
# ---------------------------------------------------------------------------

def _build_collection_plan(report_type: str, parameters: dict) -> list[dict]:
    framework_id = parameters.get("framework_id")
    risk_id = parameters.get("risk_id")
    control_id = parameters.get("control_id")
    risk_level = parameters.get("risk_level")
    risk_status = parameters.get("risk_status")
    task_status = parameters.get("task_status")
    task_priority = parameters.get("task_priority")
    org_id = parameters.get("org_id")
    top_n = parameters.get("top_n", 20)

    # ── Framework-scoped report types ─────────────────────────────────────────
    if report_type == ReportType.FRAMEWORK_COMPLIANCE:
        if framework_id:
            return [
                {"tool": "grc_framework_health", "args": {"framework_id": framework_id, "scope_org_id": org_id}},
                {"tool": "grc_requirement_gaps", "args": {"framework_id": framework_id, "gaps_only": False}},
                {"tool": "grc_risk_concentration", "args": {"framework_id": framework_id, "top_n": top_n}},
                {"tool": "grc_task_health", "args": {}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "limit": 50}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "missing_owner": True, "limit": 20}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "missing_tests": True, "limit": 20}},
            ]
        return [
            {"tool": "grc_list_frameworks", "args": {"limit": 20}},
            {"tool": "grc_framework_health", "args": {}},
            {"tool": "grc_task_health", "args": {}},
            {"tool": "grc_risk_concentration", "args": {"top_n": top_n}},
        ]

    if report_type == ReportType.FRAMEWORK_READINESS:
        if framework_id:
            return [
                {"tool": "grc_framework_health", "args": {"framework_id": framework_id, "scope_org_id": org_id}},
                {"tool": "grc_requirement_gaps", "args": {"framework_id": framework_id, "gaps_only": False}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "limit": 50}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "missing_tests": True, "limit": 30}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "missing_owner": True, "limit": 30}},
                {"tool": "grc_risk_concentration", "args": {"framework_id": framework_id, "top_n": 20}},
                {"tool": "grc_task_health", "args": {}},
            ]
        return [
            {"tool": "grc_list_frameworks", "args": {"limit": 20}},
            {"tool": "grc_framework_health", "args": {"scope_org_id": org_id}},
            {"tool": "grc_task_health", "args": {}},
        ]

    if report_type == ReportType.FRAMEWORK_GAP_ANALYSIS:
        if framework_id:
            return [
                {"tool": "grc_framework_health", "args": {"framework_id": framework_id, "scope_org_id": org_id}},
                {"tool": "grc_requirement_gaps", "args": {"framework_id": framework_id, "gaps_only": False}},
                {"tool": "grc_requirement_gaps", "args": {"framework_id": framework_id, "gaps_only": True}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "limit": 50}},
                {"tool": "grc_control_health", "args": {"missing_tests": True, "framework_id": framework_id, "limit": 30}},
                {"tool": "grc_risk_concentration", "args": {"framework_id": framework_id, "top_n": top_n}},
            ]
        return [
            {"tool": "grc_list_frameworks", "args": {"limit": 20}},
            {"tool": "grc_framework_health", "args": {"scope_org_id": org_id}},
            {"tool": "grc_task_health", "args": {}},
        ]

    # ── Control-scoped report types ────────────────────────────────────────────
    if report_type == ReportType.CONTROL_STATUS:
        if control_id:
            # Deep-dive on a single control
            return [
                {"tool": "grc_get_control", "args": {"control_id": control_id}},
                {"tool": "grc_get_control_hierarchy", "args": {"control_id": control_id}},
                {"tool": "grc_list_tasks_for_entity", "args": {"entity_type": "control", "entity_id": control_id, "include_indirect": True, "limit": 50}},
                {"tool": "grc_risk_concentration", "args": {"framework_id": framework_id, "top_n": 10}} if framework_id else {"tool": "grc_task_health", "args": {}},
            ]
        return [
            {"tool": "grc_control_health", "args": {"framework_id": framework_id, "limit": 50}},
            {"tool": "grc_control_health", "args": {"missing_owner": True, "framework_id": framework_id, "limit": 30}},
            {"tool": "grc_control_health", "args": {"missing_tests": True, "framework_id": framework_id, "limit": 30}},
            {"tool": "grc_control_health", "args": {"has_overdue_tasks": True, "framework_id": framework_id, "limit": 20}},
            {"tool": "grc_list_controls", "args": {"framework_id": framework_id, "criticality_code": "critical", "limit": 30}},
            {"tool": "grc_task_health", "args": {}},
        ]

    if report_type == ReportType.EVIDENCE_REPORT:
        if control_id:
            return [
                {"tool": "grc_get_control", "args": {"control_id": control_id}},
                {"tool": "grc_get_control_hierarchy", "args": {"control_id": control_id}},
                {"tool": "grc_list_tasks_for_entity", "args": {"entity_type": "control", "entity_id": control_id, "include_indirect": True, "limit": 50}},
            ]
        if framework_id:
            return [
                {"tool": "grc_framework_health", "args": {"framework_id": framework_id}},
                {"tool": "grc_control_health", "args": {"framework_id": framework_id, "missing_tests": True, "limit": 50}},
                {"tool": "grc_get_framework_hierarchy", "args": {"framework_id": framework_id, "has_tasks": True, "limit": 50}},
            ]
        return [
            {"tool": "grc_control_health", "args": {"missing_tests": True, "limit": 50}},
            {"tool": "grc_task_health", "args": {}},
        ]

    # ── Risk-scoped report types ───────────────────────────────────────────────
    if report_type == ReportType.RISK_SUMMARY:
        if risk_id:
            # Deep-dive on a single risk
            return [
                {"tool": "grc_get_risk", "args": {"risk_id": risk_id}},
                {"tool": "grc_get_risk_hierarchy", "args": {"risk_id": risk_id}},
                {"tool": "grc_list_tasks_for_entity", "args": {"entity_type": "risk", "entity_id": risk_id, "include_indirect": True, "limit": 50}},
            ]
        # Filtered org-wide summary
        risk_args_critical: dict = {"level_filter": "critical", "limit": 20}
        risk_args_high: dict = {"level_filter": "high", "limit": 20}
        risk_args_all: dict = {"limit": 50}
        if risk_status:
            risk_args_critical["risk_status"] = risk_status
            risk_args_high["risk_status"] = risk_status
            risk_args_all["risk_status"] = risk_status
        if risk_level:
            # If a specific level requested, focus on that level instead of scanning all
            risk_args_all["level_filter"] = risk_level
        if framework_id:
            risk_args_critical["framework_id"] = framework_id
            risk_args_high["framework_id"] = framework_id
        return [
            {"tool": "grc_list_risks", "args": risk_args_all},
            {"tool": "grc_list_risks", "args": risk_args_critical},
            {"tool": "grc_list_risks", "args": risk_args_high},
            {"tool": "grc_risk_concentration", "args": {"framework_id": framework_id, "top_n": top_n} if framework_id else {"top_n": top_n}},
            {"tool": "grc_task_health", "args": {}},
        ]

    # ── Task-scoped report types ───────────────────────────────────────────────
    if report_type == ReportType.TASK_HEALTH:
        task_filter: dict = {}
        if task_status:
            task_filter["status_filter"] = task_status
        if task_priority:
            task_filter["priority_filter"] = task_priority
        if framework_id:
            task_filter["framework_id"] = framework_id
        return [
            {"tool": "grc_task_health", "args": {}},
            {"tool": "grc_list_tasks", "args": {"overdue_only": True, "limit": 30, **({"framework_id": framework_id} if framework_id else {})}},
            {"tool": "grc_list_tasks", "args": {"priority_filter": task_priority or "critical", "limit": 20, **({"framework_id": framework_id} if framework_id else {})}},
            {"tool": "grc_list_tasks", "args": {"status_filter": task_status or "open", "limit": 30, **({"framework_id": framework_id} if framework_id else {})}},
        ]

    # ── Remediation plan — can be framework, risk-level, or priority scoped ───
    if report_type == ReportType.REMEDIATION_PLAN:
        plan = [
            {"tool": "grc_control_health", "args": {"missing_owner": True, "framework_id": framework_id, "limit": 30}},
            {"tool": "grc_control_health", "args": {"missing_tests": True, "framework_id": framework_id, "limit": 30}},
            {"tool": "grc_control_health", "args": {"has_overdue_tasks": True, "framework_id": framework_id, "limit": 30}},
            {"tool": "grc_list_risks", "args": {"level_filter": risk_level or "critical", "limit": 20, **({"risk_status": risk_status} if risk_status else {})}},
            {"tool": "grc_list_risks", "args": {"level_filter": "high", "limit": 20, **({"risk_status": risk_status} if risk_status else {})}},
            {"tool": "grc_list_tasks", "args": {"overdue_only": True, "limit": 30, **({"framework_id": framework_id} if framework_id else {})}},
            {"tool": "grc_list_tasks", "args": {"priority_filter": task_priority or "critical", "limit": 20, **({"framework_id": framework_id} if framework_id else {})}},
            {"tool": "grc_task_health", "args": {}},
        ]
        if framework_id:
            plan.insert(3, {"tool": "grc_requirement_gaps", "args": {"framework_id": framework_id, "gaps_only": True}})
        return plan

    # ── Org-wide report types ──────────────────────────────────────────────────
    if report_type == ReportType.EXECUTIVE_SUMMARY:
        return [
            {"tool": "grc_framework_health", "args": {"scope_org_id": org_id}},
            {"tool": "grc_task_health", "args": {}},
            {"tool": "grc_list_risks", "args": {"level_filter": "critical", "limit": 10}},
            {"tool": "grc_risk_concentration", "args": {"top_n": 10}},
            {"tool": "grc_control_health", "args": {"missing_owner": True, "limit": 15}},
            {"tool": "grc_list_tasks", "args": {"overdue_only": True, "limit": 15}},
        ]

    if report_type == ReportType.BOARD_RISK_REPORT:
        return [
            {"tool": "grc_framework_health", "args": {"scope_org_id": org_id}},
            {"tool": "grc_list_risks", "args": {"level_filter": risk_level or "critical", "limit": 10}},
            {"tool": "grc_list_risks", "args": {"level_filter": "high", "limit": 10}},
            {"tool": "grc_risk_concentration", "args": {"top_n": 10}},
            {"tool": "grc_task_health", "args": {}},
            {"tool": "grc_list_tasks", "args": {"overdue_only": True, "limit": 10}},
            {"tool": "grc_control_health", "args": {"min_risk_severity": risk_level or "high", "limit": 10}},
        ]

    if report_type == ReportType.AUDIT_TRAIL:
        return [
            {"tool": "grc_task_health", "args": {}},
            {"tool": "grc_list_tasks", "args": {"limit": 50, **({"framework_id": framework_id} if framework_id else {})}},
        ]

    if report_type == ReportType.COMPLIANCE_POSTURE:
        return [
            {"tool": "grc_list_frameworks", "args": {"limit": 20}},
            {"tool": "grc_framework_health", "args": {"scope_org_id": org_id}},
            {"tool": "grc_task_health", "args": {}},
            {"tool": "grc_list_risks", "args": {"level_filter": "critical", "limit": 15}},
            {"tool": "grc_risk_concentration", "args": {"top_n": top_n}},
            {"tool": "grc_control_health", "args": {"missing_owner": True, "limit": 20}},
            {"tool": "grc_control_health", "args": {"missing_tests": True, "limit": 20}},
            {"tool": "grc_list_tasks", "args": {"overdue_only": True, "limit": 20}},
        ]

    if report_type == ReportType.VENDOR_RISK:
        risk_level_filter = risk_level or "critical"
        return [
            {"tool": "grc_list_risks", "args": {"limit": 50, **({"risk_status": risk_status} if risk_status else {})}},
            {"tool": "grc_list_risks", "args": {"level_filter": risk_level_filter, "limit": 20}},
            {"tool": "grc_list_risks", "args": {"level_filter": "high", "limit": 20}},
            {"tool": "grc_risk_concentration", "args": {"top_n": top_n}},
            {"tool": "grc_control_health", "args": {"min_risk_severity": "high", "limit": 30}},
            {"tool": "grc_task_health", "args": {}},
        ]

    # Default fallback
    return [
        {"tool": "grc_framework_health", "args": {}},
        {"tool": "grc_task_health", "args": {}},
        {"tool": "grc_list_risks", "args": {"limit": 20}},
    ]


# ---------------------------------------------------------------------------
# Main agent class
# ---------------------------------------------------------------------------

class ReportGenerationAgent:

    def __init__(self, *, config, settings, pool: asyncpg.Pool) -> None:
        self._config = config
        self._settings = settings
        self._pool = pool
        self._dispatcher = MCPToolDispatcher()
        self._provider = get_provider(
            provider_type=config.provider_type,
            provider_base_url=config.provider_base_url,
            api_key=config.api_key,
            model_id=config.model_id,
        )
        self._repo = ReportRepository()
        self._pageindexer = (
            PageIndexer(settings=settings)
            if getattr(settings, "ai_pageindex_enabled", False)
            else NullPageIndexer()
        )

    async def run(self, state: ReportGenState) -> ReportGenState:
        """Run the full pipeline. Updates DB at each stage transition."""
        start = time.time()
        try:
            # Stage 1: Collect data
            await self._set_status(state, ReportStatus.COLLECTING)
            await self._stage_collect(state)

            # Stage 2: Analyze
            await self._set_status(state, ReportStatus.ANALYZING)
            await self._stage_analyze(state)

            # Stage 3: Write sections
            await self._set_status(state, ReportStatus.WRITING)
            await self._stage_write(state)

            # Stage 4: Format final markdown
            await self._set_status(state, ReportStatus.FORMATTING)
            await self._stage_format(state)

            # Persist content
            word_count = len(state.markdown_content.split())
            async with self._pool.acquire() as conn:
                await self._repo.update_report_content(
                    conn,
                    state.report_id,
                    markdown_content=state.markdown_content,
                    word_count=word_count,
                    token_count=state.tokens_consumed,
                )
            state.status = ReportStatus.COMPLETED
            duration = time.time() - start
            _logger.info(
                "report_agent.completed",
                extra={
                    "report_id": state.report_id,
                    "report_type": state.report_type,
                    "words": word_count,
                    "tokens": state.tokens_consumed,
                    "duration_s": round(duration, 1),
                },
            )
        except Exception as exc:
            state.status = ReportStatus.FAILED
            state.error = str(exc)
            _logger.exception("report_agent.failed: %s", exc)
            async with self._pool.acquire() as conn:
                await self._repo.update_report_status(
                    conn, state.report_id, ReportStatus.FAILED, error_message=str(exc)[:2000]
                )
        return state

    async def _set_status(self, state: ReportGenState, status: str) -> None:
        state.status = status
        async with self._pool.acquire() as conn:
            await self._repo.update_report_status(conn, state.report_id, status)

    # ── Stage 1: Collect ────────────────────────────────────────────────────

    async def _stage_collect(self, state: ReportGenState) -> None:
        # Merge state-level org_id/workspace_id into parameters so _build_collection_plan can use them
        merged_params = {
            "org_id": state.org_id,
            "workspace_id": state.workspace_id,
            **state.parameters,
        }
        plan = _build_collection_plan(state.report_type, merged_params)
        state.plan = {"tool_calls": plan}

        # Build ToolContext
        ctx = await self._build_tool_context(state)
        collected: dict[str, Any] = {}

        for call in plan[:_MAX_TOOL_CALLS]:
            tool_name = call["tool"]
            args = call.get("args", {})
            try:
                result = await self._dispatcher.dispatch(tool_name, args, ctx)
                key = f"{tool_name}__{json.dumps(args, sort_keys=True, default=str)[:40]}"
                collected[key] = result.output
                state.tokens_consumed += result.token_estimate
                _logger.debug("report_agent.tool_ok: %s", tool_name)
            except Exception as exc:
                _logger.warning("report_agent.tool_error %s: %s", tool_name, exc)
                collected[f"{tool_name}__error"] = {"error": str(exc)}

        state.collected_data = collected

    async def _build_tool_context(self, state: ReportGenState) -> ToolContext:
        # Import services lazily
        _fw_svc_mod = import_module("backend.05_grc_library.02_frameworks.service")
        _req_svc_mod = import_module("backend.05_grc_library.04_requirements.service")
        _ctrl_svc_mod = import_module("backend.05_grc_library.05_controls.service")
        _risk_svc_mod = import_module("backend.06_risk_registry.02_risks.service")
        _task_svc_mod = import_module("backend.07_tasks.02_tasks.service")

        _null_cache = NullCacheManager()
        fw_svc = _fw_svc_mod.FrameworkService(settings=self._settings, database_pool=self._pool, cache=_null_cache)
        req_svc = _req_svc_mod.RequirementService(settings=self._settings, database_pool=self._pool, cache=_null_cache)
        ctrl_svc = _ctrl_svc_mod.ControlService(settings=self._settings, database_pool=self._pool, cache=_null_cache)
        risk_svc = _risk_svc_mod.RiskService(settings=self._settings, database_pool=self._pool, cache=_null_cache)
        task_svc = _task_svc_mod.TaskService(settings=self._settings, database_pool=self._pool, cache=_null_cache)

        return ToolContext(
            pool=self._pool,
            user_id=state.user_id,
            tenant_key=state.tenant_key,
            org_id=state.org_id,
            workspace_id=state.workspace_id,
            framework_service=fw_svc,
            requirement_service=req_svc,
            control_service=ctrl_svc,
            risk_service=risk_svc,
            task_service=task_svc,
        )

    # ── Stage 2: Analyze ────────────────────────────────────────────────────

    async def _stage_analyze(self, state: ReportGenState) -> None:
        data_text = json.dumps(state.collected_data, indent=2, default=str)

        # Compress large payloads via PageIndexer if enabled
        try:
            compressed = await self._pageindexer.compress(data_text)
        except Exception:
            compressed = data_text[:8000]

        messages = [
            {"role": "system", "content": _ANALYSIS_SYSTEM},
            {
                "role": "user",
                "content": (
                    f"Report type: {state.report_type}\n"
                    f"Parameters: {json.dumps(state.parameters, default=str)}\n\n"
                    f"Collected GRC data:\n{compressed}\n\n"
                    "Analyze this data and produce the structured JSON output."
                ),
            },
        ]
        response = await self._provider.chat_completion(
            messages=messages,
            temperature=1.0,
            max_tokens=_ANALYSIS_MAX_TOKENS,
        )
        state.tokens_consumed += response.input_tokens + response.output_tokens
        raw = (response.content or "{}").strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        try:
            state.analysis = json.loads(raw)
        except json.JSONDecodeError:
            _logger.warning("report_agent.analyze_parse_error — using raw text")
            state.analysis = {"raw_analysis": raw}

    # ── Stage 3: Write sections ─────────────────────────────────────────────

    async def _stage_write(self, state: ReportGenState) -> None:
        sections_to_write = REPORT_SECTIONS.get(state.report_type, ["executive_summary", "details", "recommendations"])
        written_sections = []
        for section_key in sections_to_write:
            prompt = _section_prompt(
                section_key, state.report_type, state.analysis, state.collected_data
            )
            messages = [
                {"role": "system", "content": _SECTION_WRITER_SYSTEM},
                {"role": "user", "content": prompt},
            ]
            try:
                response = await self._provider.chat_completion(
                    messages=messages,
                    temperature=1.0,
                    max_tokens=_SECTION_MAX_TOKENS,
                )
                state.tokens_consumed += response.input_tokens + response.output_tokens
                content = (response.content or "").strip()
            except Exception as exc:
                _logger.warning("report_agent.section_write_error %s: %s", section_key, exc)
                content = f"*Section could not be generated: {exc}*"

            written_sections.append({"key": section_key, "content": content})

        state.sections = written_sections

    # ── Stage 4: Format ─────────────────────────────────────────────────────

    async def _stage_format(self, state: ReportGenState) -> None:
        state.markdown_content = _assemble_markdown(state)


# ---------------------------------------------------------------------------
# Markdown assembler
# ---------------------------------------------------------------------------

def _section_heading(section_key: str) -> str:
    return section_key.replace("_", " ").title()


def _assemble_markdown(state: ReportGenState) -> str:
    lines: list[str] = []
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    report_label = REPORT_TYPE_LABELS.get(state.report_type, state.report_type.replace("_", " ").title())
    title = state.parameters.get("title") or report_label

    # ── Cover ────────────────────────────────────────────────────────────────
    lines += [
        f"# {title}",
        "",
        f"> **Report Type:** {report_label}  ",
        f"> **Organization ID:** `{state.org_id}`  ",
        f"> **Generated:** {now}  ",
        "> **Generated by:** K-Control AI Report Generator  ",
        "",
    ]

    # Headline from analysis if available
    headline = state.analysis.get("executive_headline")
    if headline:
        lines += [f"> 💡 **{headline}**", ""]

    # Key metrics table from analysis
    metrics = state.analysis.get("key_metrics", {})
    if metrics:
        lines += ["## Key Metrics", ""]
        lines += ["| Metric | Value |", "|---|---|"]
        for k, v in list(metrics.items())[:10]:
            lines.append(f"| {k.replace('_', ' ').title()} | {v} |")
        lines.append("")

    # Critical findings callouts
    findings = state.analysis.get("critical_findings", [])
    if findings:
        lines += ["## ⚠ Critical Findings", ""]
        for f in findings[:5]:
            sev = f.get("severity", "high").upper()
            icon = "🔴" if sev == "CRITICAL" else "🟠" if sev == "HIGH" else "🟡"
            lines.append(f"> {icon} **{sev}:** {f.get('finding', '')}  ")
            rec = f.get("recommendation")
            if rec:
                lines.append(f"> *Recommendation: {rec}*  ")
        lines.append("")

    # Table of contents
    sections_to_write = REPORT_SECTIONS.get(state.report_type, [])
    if sections_to_write:
        lines += ["## Table of Contents", ""]
        for i, sec in enumerate(sections_to_write, 1):
            anchor = sec.replace("_", "-")
            lines.append(f"{i}. [{_section_heading(sec)}](#{anchor})")
        lines.append("")

    lines += ["---", ""]

    # ── Sections ────────────────────────────────────────────────────────────
    for sec in state.sections:
        heading = _section_heading(sec["key"])
        anchor = sec["key"].replace("_", "-")
        lines += [f"## {heading} {{#{anchor}}}", "", sec["content"], ""]

    # ── Strengths ────────────────────────────────────────────────────────────
    strengths = state.analysis.get("strengths", [])
    if strengths:
        lines += ["---", "", "## Areas of Strength", ""]
        for s in strengths:
            lines.append(f"- ✅ {s}")
        lines.append("")

    # ── Footer ───────────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        f"*Report generated by K-Control AI · {now}*  ",
        f"*Tokens consumed: {state.tokens_consumed:,}*  ",
        "",
        "> ⚠️ This report is AI-generated. All findings should be reviewed by a "
        "qualified compliance professional before use in audit or regulatory submissions.",
        "",
    ]

    return "\n".join(lines)
