-- =============================================================================
-- Migration:   20260409_021_kbio_tables.sql
-- Module:      10_kbio
-- Sub-feature: 00_bootstrap
-- Sequence:    021
-- Depends on:  020 (10_kbio/00_bootstrap)
-- Description: Create fact, detail, link, and event tables for kbio behavioral
--              intelligence. Sessions, devices, profiles, trusted entities,
--              challenges, predefined policies, and all event logs.
-- =============================================================================

-- UP =========================================================================

-- ---------------------------------------------------------------------------
-- 10_fct_sessions — SDK session tracking
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."10_fct_sessions" (
    id                  VARCHAR(36)   NOT NULL,
    sdk_session_id      VARCHAR(36)   NOT NULL,
    user_hash           VARCHAR(64)   NOT NULL,
    device_uuid         VARCHAR(36)   NOT NULL,
    status_id           SMALLINT      NOT NULL DEFAULT 1,
    trust_level_id      SMALLINT      NOT NULL DEFAULT 1,
    baseline_quality_id SMALLINT      NOT NULL DEFAULT 1,
    is_active           BOOLEAN       NOT NULL DEFAULT TRUE,
    is_test             BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP,
    created_by          VARCHAR(36)   NOT NULL,
    updated_by          VARCHAR(36)   NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_fct_sessions              PRIMARY KEY (id),
    CONSTRAINT uq_kbio_fct_sessions_sdk_sid      UNIQUE (sdk_session_id),
    CONSTRAINT fk_kbio_fct_sessions_status       FOREIGN KEY (status_id)
                                                  REFERENCES "10_kbio"."01_dim_session_statuses" (id),
    CONSTRAINT fk_kbio_fct_sessions_trust        FOREIGN KEY (trust_level_id)
                                                  REFERENCES "10_kbio"."03_dim_trust_levels" (id),
    CONSTRAINT fk_kbio_fct_sessions_baseline     FOREIGN KEY (baseline_quality_id)
                                                  REFERENCES "10_kbio"."05_dim_baseline_qualities" (id)
);

CREATE INDEX idx_kbio_fct_sessions_user_hash   ON "10_kbio"."10_fct_sessions" (user_hash);
CREATE INDEX idx_kbio_fct_sessions_device_uuid ON "10_kbio"."10_fct_sessions" (device_uuid);
CREATE INDEX idx_kbio_fct_sessions_created_at  ON "10_kbio"."10_fct_sessions" (created_at DESC);

COMMENT ON TABLE  "10_kbio"."10_fct_sessions" IS
    'SDK session tracking. One row per active SDK session initiated from the client. '
    'sdk_session_id, user_hash, and device_uuid are scope/routing columns required for '
    'sub-millisecond lookup on every ingest request — they are not business data stored '
    'outside EAV for convenience.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".id                  IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".sdk_session_id      IS 'Unique session identifier assigned by the SDK client. Scope/routing column.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".user_hash           IS 'Pseudonymous user identifier (HMAC-SHA256 of canonical user ID). Scope/routing column.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".device_uuid         IS 'Stable device identifier generated by the SDK. Scope/routing column.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".status_id           IS 'FK → 01_dim_session_statuses. Lifecycle state (active, completed, expired, etc.).';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".trust_level_id      IS 'FK → 03_dim_trust_levels. Current computed trust level for the session.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".baseline_quality_id IS 'FK → 05_dim_baseline_qualities. Quality grade of the behavioral baseline for this session.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".is_active           IS 'FALSE once the session is terminated or expired.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".is_test             IS 'TRUE for synthetic or load-test sessions. Excluded from production analytics.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".deleted_at          IS 'Soft-delete timestamp. NULL means not deleted.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".created_by          IS 'UUID of the actor or service that created this row.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".updated_by          IS 'UUID of the actor or service that last updated this row.';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".created_at          IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."10_fct_sessions".updated_at          IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."10_fct_sessions" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."10_fct_sessions" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 11_fct_devices — Device registry
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."11_fct_devices" (
    id          VARCHAR(36)   NOT NULL,
    device_uuid VARCHAR(36)   NOT NULL,
    user_hash   VARCHAR(64),
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    is_test     BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP,
    created_by  VARCHAR(36)   NOT NULL,
    updated_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_fct_devices              PRIMARY KEY (id),
    CONSTRAINT uq_kbio_fct_devices_device_uuid  UNIQUE (device_uuid)
);

CREATE INDEX idx_kbio_fct_devices_user_hash ON "10_kbio"."11_fct_devices" (user_hash);

COMMENT ON TABLE  "10_kbio"."11_fct_devices" IS
    'Device registry. One row per unique SDK-generated device identifier. '
    'A device may be created before a user is identified, hence user_hash is nullable.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".id          IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".device_uuid IS 'Stable device identifier from the SDK. Scope/routing column for fast ingest lookup.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".user_hash   IS 'First user_hash observed on this device. NULL when device precedes user identification.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".is_active   IS 'FALSE when the device is deregistered or permanently blocked.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".is_test     IS 'TRUE for emulators or synthetic test devices.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".deleted_at  IS 'Soft-delete timestamp. NULL means not deleted.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".created_by  IS 'UUID of the actor or service that created this row.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".updated_by  IS 'UUID of the actor or service that last updated this row.';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".created_at  IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."11_fct_devices".updated_at  IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."11_fct_devices" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."11_fct_devices" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 12_fct_user_profiles — Behavioral user profile identity
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."12_fct_user_profiles" (
    id                  VARCHAR(36)   NOT NULL,
    user_hash           VARCHAR(64)   NOT NULL,
    baseline_quality_id SMALLINT      NOT NULL DEFAULT 1,
    is_active           BOOLEAN       NOT NULL DEFAULT TRUE,
    is_test             BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP,
    created_by          VARCHAR(36)   NOT NULL,
    updated_by          VARCHAR(36)   NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_fct_user_profiles              PRIMARY KEY (id),
    CONSTRAINT uq_kbio_fct_user_profiles_user_hash    UNIQUE (user_hash),
    CONSTRAINT fk_kbio_fct_user_profiles_baseline     FOREIGN KEY (baseline_quality_id)
                                                       REFERENCES "10_kbio"."05_dim_baseline_qualities" (id)
);

COMMENT ON TABLE  "10_kbio"."12_fct_user_profiles" IS
    'Behavioral user profile identity. One row per pseudonymous user. '
    'Anchors EAV attributes (learned baselines, typing cadence, mouse dynamics) '
    'and is the parent for all per-user behavioral state.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".id                  IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".user_hash           IS 'Pseudonymous user identifier. Scope/routing column. Unique per profile.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".baseline_quality_id IS 'FK → 05_dim_baseline_qualities. Overall quality grade of the learned behavioral baseline.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".is_active           IS 'FALSE when the profile is suspended or removed.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".is_test             IS 'TRUE for synthetic test profiles. Excluded from production analytics.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".deleted_at          IS 'Soft-delete timestamp. NULL means not deleted.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".created_by          IS 'UUID of the actor or service that created this row.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".updated_by          IS 'UUID of the actor or service that last updated this row.';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".created_at          IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."12_fct_user_profiles".updated_at          IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."12_fct_user_profiles" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."12_fct_user_profiles" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 13_fct_trusted_entities — Trusted devices, IPs, locations, networks
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."13_fct_trusted_entities" (
    id              VARCHAR(36)   NOT NULL,
    user_hash       VARCHAR(64)   NOT NULL,
    entity_type_id  SMALLINT      NOT NULL,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    is_test         BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP,
    created_by      VARCHAR(36)   NOT NULL,
    updated_by      VARCHAR(36)   NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_fct_trusted_entities             PRIMARY KEY (id),
    CONSTRAINT fk_kbio_fct_trusted_entities_entity_type FOREIGN KEY (entity_type_id)
                                                         REFERENCES "10_kbio"."09_dim_trusted_entity_types" (id)
);

CREATE INDEX idx_kbio_fct_trusted_entities_user_hash    ON "10_kbio"."13_fct_trusted_entities" (user_hash);
CREATE INDEX idx_kbio_fct_trusted_entities_entity_type  ON "10_kbio"."13_fct_trusted_entities" (entity_type_id);

COMMENT ON TABLE  "10_kbio"."13_fct_trusted_entities" IS
    'Trusted entity registry. Tracks devices, IP addresses, geographic locations, '
    'and network ranges that a user has explicitly or implicitly trusted. '
    'The entity value (IP, location hash, etc.) is stored via EAV in 20_dtl_attrs.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".id              IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".user_hash       IS 'Pseudonymous user identifier. Scope column — trust is user-scoped.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".entity_type_id  IS 'FK → 09_dim_trusted_entity_types. Discriminates device / ip / location / network.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".is_active       IS 'FALSE when trust is revoked.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".is_test         IS 'TRUE for test/synthetic trust entries.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".deleted_at      IS 'Soft-delete timestamp. NULL means not deleted.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".created_by      IS 'UUID of the actor or service that created this row.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".updated_by      IS 'UUID of the actor or service that last updated this row.';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".created_at      IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."13_fct_trusted_entities".updated_at      IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."13_fct_trusted_entities" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."13_fct_trusted_entities" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 14_fct_challenges — KP-Challenge instances
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."14_fct_challenges" (
    id              VARCHAR(36)   NOT NULL,
    sdk_session_id  VARCHAR(36)   NOT NULL,
    user_hash       VARCHAR(64)   NOT NULL,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    is_test         BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP,
    created_by      VARCHAR(36)   NOT NULL,
    updated_by      VARCHAR(36)   NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_fct_challenges PRIMARY KEY (id)
);

CREATE INDEX idx_kbio_fct_challenges_sdk_session_id ON "10_kbio"."14_fct_challenges" (sdk_session_id);
CREATE INDEX idx_kbio_fct_challenges_user_hash      ON "10_kbio"."14_fct_challenges" (user_hash);

COMMENT ON TABLE  "10_kbio"."14_fct_challenges" IS
    'KP-Challenge instances. One row per behavioral challenge issued to a user session. '
    'The row id doubles as the challenge_id returned to the SDK. '
    'Challenge type, status, and result are stored via EAV in 20_dtl_attrs.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".id              IS 'UUID v7 primary key. Also serves as the challenge_id returned to the SDK client.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".sdk_session_id  IS 'SDK session that triggered this challenge. Scope/routing column.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".user_hash       IS 'Pseudonymous user under challenge. Scope/routing column.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".is_active       IS 'FALSE once the challenge is resolved (passed, failed, expired, or cancelled).';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".is_test         IS 'TRUE for synthetic challenges issued during integration testing.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".deleted_at      IS 'Soft-delete timestamp. NULL means not deleted.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".created_by      IS 'UUID of the actor or service that created this row.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".updated_by      IS 'UUID of the actor or service that last updated this row.';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".created_at      IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."14_fct_challenges".updated_at      IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."14_fct_challenges" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."14_fct_challenges" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 15_fct_predefined_policies — Predefined policy library
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."15_fct_predefined_policies" (
    id          VARCHAR(36)   NOT NULL,
    category_id SMALLINT      NOT NULL,
    action_id   SMALLINT      NOT NULL,
    severity    SMALLINT      NOT NULL DEFAULT 50,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    is_test     BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP,
    created_by  VARCHAR(36)   NOT NULL,
    updated_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_fct_predefined_policies              PRIMARY KEY (id),
    CONSTRAINT fk_kbio_fct_predefined_policies_category     FOREIGN KEY (category_id)
                                                             REFERENCES "10_kbio"."06_dim_policy_categories" (id),
    CONSTRAINT fk_kbio_fct_predefined_policies_action       FOREIGN KEY (action_id)
                                                             REFERENCES "10_kbio"."04_dim_drift_actions" (id),
    CONSTRAINT chk_kbio_fct_predefined_policies_severity    CHECK (severity BETWEEN 0 AND 100)
);

CREATE INDEX idx_kbio_fct_predefined_policies_category ON "10_kbio"."15_fct_predefined_policies" (category_id);
CREATE INDEX idx_kbio_fct_predefined_policies_severity ON "10_kbio"."15_fct_predefined_policies" (severity);

COMMENT ON TABLE  "10_kbio"."15_fct_predefined_policies" IS
    'Predefined policy library. System-provided drift response policies that tenants '
    'can adopt or override. Policy name, description, and rule configuration are '
    'stored via EAV in 20_dtl_attrs.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".id          IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".category_id IS 'FK → 06_dim_policy_categories. Groups policies by domain (auth, fraud, compliance, etc.).';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".action_id   IS 'FK → 04_dim_drift_actions. Default enforcement action (alert, challenge, block, etc.).';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".severity    IS 'Ordinal severity 0-100. Used for listing and priority resolution.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".is_active   IS 'FALSE when the policy is retired from the library.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".is_test     IS 'TRUE for sandbox-only policies used in integration tests.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".deleted_at  IS 'Soft-delete timestamp. NULL means not deleted.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".created_by  IS 'UUID of the actor or service that created this row.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".updated_by  IS 'UUID of the actor or service that last updated this row.';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".created_at  IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."15_fct_predefined_policies".updated_at  IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."15_fct_predefined_policies" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."15_fct_predefined_policies" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 20_dtl_attrs — Shared EAV store
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."20_dtl_attrs" (
    id              VARCHAR(36)   NOT NULL,
    entity_type_id  SMALLINT      NOT NULL,
    entity_id       VARCHAR(36)   NOT NULL,
    attr_def_id     SMALLINT      NOT NULL,
    key_text        TEXT,
    key_jsonb       JSONB,
    key_smallint    SMALLINT,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_dtl_attrs               PRIMARY KEY (id),
    CONSTRAINT fk_kbio_dtl_attrs_etype         FOREIGN KEY (entity_type_id)
                                                REFERENCES "10_kbio"."06_dim_entity_types" (id),
    CONSTRAINT fk_kbio_dtl_attrs_attr_def      FOREIGN KEY (attr_def_id)
                                                REFERENCES "10_kbio"."07_dim_attr_defs" (id),
    CONSTRAINT uq_kbio_dtl_attrs_entity_attr   UNIQUE (entity_id, attr_def_id),
    CONSTRAINT chk_kbio_dtl_attrs_one_value    CHECK (
        (key_text IS NOT NULL)::int +
        (key_jsonb IS NOT NULL)::int +
        (key_smallint IS NOT NULL)::int = 1
    )
);

CREATE INDEX idx_kbio_dtl_attrs_entity ON "10_kbio"."20_dtl_attrs" (entity_type_id, entity_id);

COMMENT ON TABLE  "10_kbio"."20_dtl_attrs" IS
    'Shared EAV (Entity-Attribute-Value) store for the kbio schema. '
    'Stores all flexible attributes for sessions, devices, user profiles, '
    'trusted entities, challenges, and predefined policies without widening '
    'the corresponding fct_* tables. Every attribute key must be pre-registered '
    'in 07_dim_attr_defs before use.';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".id              IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".entity_type_id  IS 'FK → 06_dim_entity_types. Identifies which fct_* table the entity_id belongs to.';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".entity_id       IS 'UUID of the parent entity (session, device, profile, etc.).';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".attr_def_id     IS 'FK → 07_dim_attr_defs. Identifies the attribute definition (name, type, validation).';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".key_text        IS 'String attribute value. Exactly one of key_text / key_jsonb / key_smallint must be non-NULL.';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".key_jsonb       IS 'JSON object/array attribute value. Exactly one of key_text / key_jsonb / key_smallint must be non-NULL.';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".key_smallint    IS 'FK-to-dim integer attribute value. Exactly one of key_text / key_jsonb / key_smallint must be non-NULL.';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".created_at      IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN "10_kbio"."20_dtl_attrs".updated_at      IS 'Row last-update timestamp (UTC). Managed by trigger.';

GRANT SELECT                            ON "10_kbio"."20_dtl_attrs" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE    ON "10_kbio"."20_dtl_attrs" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 40_lnk_user_devices — user_hash ↔ device_id
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."40_lnk_user_devices" (
    id          VARCHAR(36)   NOT NULL,
    user_hash   VARCHAR(64)   NOT NULL,
    device_id   VARCHAR(36)   NOT NULL,
    created_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_lnk_user_devices             PRIMARY KEY (id),
    CONSTRAINT uq_kbio_lnk_user_devices_user_device UNIQUE (user_hash, device_id),
    CONSTRAINT fk_kbio_lnk_user_devices_device      FOREIGN KEY (device_id)
                                                     REFERENCES "10_kbio"."11_fct_devices" (id)
);

CREATE INDEX idx_kbio_lnk_user_devices_user_hash ON "10_kbio"."40_lnk_user_devices" (user_hash);
CREATE INDEX idx_kbio_lnk_user_devices_device_id ON "10_kbio"."40_lnk_user_devices" (device_id);

COMMENT ON TABLE  "10_kbio"."40_lnk_user_devices" IS
    'Many-to-many link between pseudonymous users (user_hash) and registered devices. '
    'Rows are immutable — revoke access by deactivating the device in 11_fct_devices. '
    'No updated_at per link table convention.';
COMMENT ON COLUMN "10_kbio"."40_lnk_user_devices".id         IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."40_lnk_user_devices".user_hash  IS 'Pseudonymous user identifier linked to this device.';
COMMENT ON COLUMN "10_kbio"."40_lnk_user_devices".device_id  IS 'FK → 11_fct_devices. Device linked to this user.';
COMMENT ON COLUMN "10_kbio"."40_lnk_user_devices".created_by IS 'UUID of the actor or service that created this link.';
COMMENT ON COLUMN "10_kbio"."40_lnk_user_devices".created_at IS 'Row creation timestamp (UTC).';

GRANT SELECT                    ON "10_kbio"."40_lnk_user_devices" TO tennetctl_read;
GRANT SELECT, INSERT            ON "10_kbio"."40_lnk_user_devices" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 41_lnk_session_devices — session_id ↔ device_id
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."41_lnk_session_devices" (
    id          VARCHAR(36)   NOT NULL,
    session_id  VARCHAR(36)   NOT NULL,
    device_id   VARCHAR(36)   NOT NULL,
    created_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_lnk_session_devices              PRIMARY KEY (id),
    CONSTRAINT uq_kbio_lnk_session_devices_session_dev  UNIQUE (session_id, device_id),
    CONSTRAINT fk_kbio_lnk_session_devices_session      FOREIGN KEY (session_id)
                                                         REFERENCES "10_kbio"."10_fct_sessions" (id),
    CONSTRAINT fk_kbio_lnk_session_devices_device       FOREIGN KEY (device_id)
                                                         REFERENCES "10_kbio"."11_fct_devices" (id)
);

CREATE INDEX idx_kbio_lnk_session_devices_session_id ON "10_kbio"."41_lnk_session_devices" (session_id);
CREATE INDEX idx_kbio_lnk_session_devices_device_id  ON "10_kbio"."41_lnk_session_devices" (device_id);

COMMENT ON TABLE  "10_kbio"."41_lnk_session_devices" IS
    'Many-to-many link between sessions and devices. Records which device(s) were '
    'active during a given session. Immutable — no updated_at per link table convention.';
COMMENT ON COLUMN "10_kbio"."41_lnk_session_devices".id         IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."41_lnk_session_devices".session_id IS 'FK → 10_fct_sessions. The session in this association.';
COMMENT ON COLUMN "10_kbio"."41_lnk_session_devices".device_id  IS 'FK → 11_fct_devices. The device in this association.';
COMMENT ON COLUMN "10_kbio"."41_lnk_session_devices".created_by IS 'UUID of the actor or service that created this link.';
COMMENT ON COLUMN "10_kbio"."41_lnk_session_devices".created_at IS 'Row creation timestamp (UTC).';

GRANT SELECT                    ON "10_kbio"."41_lnk_session_devices" TO tennetctl_read;
GRANT SELECT, INSERT            ON "10_kbio"."41_lnk_session_devices" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 60_evt_score_events — Every drift score calculation
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."60_evt_score_events" (
    id              VARCHAR(36)   NOT NULL,
    session_id      VARCHAR(36)   NOT NULL,
    user_hash       VARCHAR(64)   NOT NULL,
    batch_id        VARCHAR(36)   NOT NULL,
    batch_type_id   SMALLINT      NOT NULL,
    drift_action_id SMALLINT      NOT NULL,
    metadata        JSONB,
    created_by      VARCHAR(36)   NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_evt_score_events              PRIMARY KEY (id),
    CONSTRAINT uq_kbio_evt_score_events_batch_id     UNIQUE (batch_id),
    CONSTRAINT fk_kbio_evt_score_events_batch_type   FOREIGN KEY (batch_type_id)
                                                      REFERENCES "10_kbio"."02_dim_batch_types" (id),
    CONSTRAINT fk_kbio_evt_score_events_drift_action FOREIGN KEY (drift_action_id)
                                                      REFERENCES "10_kbio"."04_dim_drift_actions" (id)
);

CREATE INDEX idx_kbio_evt_score_events_session_created ON "10_kbio"."60_evt_score_events" (session_id, created_at DESC);
CREATE INDEX idx_kbio_evt_score_events_user_created    ON "10_kbio"."60_evt_score_events" (user_hash, created_at DESC);

COMMENT ON TABLE  "10_kbio"."60_evt_score_events" IS
    'Append-only log of every behavioral drift score calculation. One row per batch '
    'processed by the scoring engine. batch_id provides idempotency — re-delivery of '
    'the same batch must be deduplicated at insert time. No updated_at, no deleted_at.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".id              IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".session_id      IS 'The session being scored. Not a FK — avoids join overhead on hot ingest path.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".user_hash       IS 'Pseudonymous user identifier. Denormalized for fast per-user timeline queries.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".batch_id        IS 'Idempotency key from the SDK batch submission. Must be unique across all score events.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".batch_type_id   IS 'FK → 02_dim_batch_types. Identifies the signal modality (keystroke, mouse, touch, etc.).';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".drift_action_id IS 'FK → 04_dim_drift_actions. Action triggered by this score (alert, challenge, block, pass).';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".metadata        IS 'Scoring detail bag: drift_score, confidence, signal_scores, fusion_weights, model version, etc.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".created_by      IS 'UUID of the scoring service that wrote this row.';
COMMENT ON COLUMN "10_kbio"."60_evt_score_events".created_at      IS 'Row creation timestamp (UTC).';

GRANT SELECT            ON "10_kbio"."60_evt_score_events" TO tennetctl_read;
GRANT SELECT, INSERT    ON "10_kbio"."60_evt_score_events" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 61_evt_anomaly_events — Trust level changes, alerts
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."61_evt_anomaly_events" (
    id          VARCHAR(36)   NOT NULL,
    session_id  VARCHAR(36)   NOT NULL,
    user_hash   VARCHAR(64)   NOT NULL,
    severity_id SMALLINT      NOT NULL,
    metadata    JSONB,
    created_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_evt_anomaly_events           PRIMARY KEY (id),
    CONSTRAINT fk_kbio_evt_anomaly_events_severity  FOREIGN KEY (severity_id)
                                                     REFERENCES "10_kbio"."08_dim_alert_severities" (id)
);

CREATE INDEX idx_kbio_evt_anomaly_events_session_created ON "10_kbio"."61_evt_anomaly_events" (session_id, created_at DESC);
CREATE INDEX idx_kbio_evt_anomaly_events_user_created    ON "10_kbio"."61_evt_anomaly_events" (user_hash, created_at DESC);
CREATE INDEX idx_kbio_evt_anomaly_events_severity        ON "10_kbio"."61_evt_anomaly_events" (severity_id);

COMMENT ON TABLE  "10_kbio"."61_evt_anomaly_events" IS
    'Append-only log of trust level changes and behavioral anomaly alerts. '
    'One row per detected anomaly or trust transition. No updated_at, no deleted_at.';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".id          IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".session_id  IS 'The session in which the anomaly was detected. Not a FK — hot ingest path.';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".user_hash   IS 'Pseudonymous user identifier. Denormalized for fast per-user anomaly timeline.';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".severity_id IS 'FK → 08_dim_alert_severities. Alert severity (info, low, medium, high, critical).';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".metadata    IS 'Anomaly detail bag: alert_type, description, drift_score, previous_trust_level, new_trust_level, trigger details.';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".created_by  IS 'UUID of the service that detected and wrote this anomaly.';
COMMENT ON COLUMN "10_kbio"."61_evt_anomaly_events".created_at  IS 'Row creation timestamp (UTC).';

GRANT SELECT            ON "10_kbio"."61_evt_anomaly_events" TO tennetctl_read;
GRANT SELECT, INSERT    ON "10_kbio"."61_evt_anomaly_events" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 62_evt_bot_detection_events — Bot detection results
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."62_evt_bot_detection_events" (
    id          VARCHAR(36)   NOT NULL,
    session_id  VARCHAR(36)   NOT NULL,
    user_hash   VARCHAR(64)   NOT NULL,
    batch_id    VARCHAR(36)   NOT NULL,
    metadata    JSONB,
    created_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_evt_bot_detection_events          PRIMARY KEY (id),
    CONSTRAINT uq_kbio_evt_bot_detection_events_batch_id UNIQUE (batch_id)
);

CREATE INDEX idx_kbio_evt_bot_detection_events_session_created ON "10_kbio"."62_evt_bot_detection_events" (session_id, created_at DESC);
CREATE INDEX idx_kbio_evt_bot_detection_events_user_created    ON "10_kbio"."62_evt_bot_detection_events" (user_hash, created_at DESC);

COMMENT ON TABLE  "10_kbio"."62_evt_bot_detection_events" IS
    'Append-only log of bot detection results. One row per evaluated batch. '
    'batch_id provides idempotency against SDK re-delivery. No updated_at, no deleted_at.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".id          IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".session_id  IS 'The session evaluated for bot activity. Not a FK — hot ingest path.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".user_hash   IS 'Pseudonymous user identifier. Denormalized for fast per-user query.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".batch_id    IS 'Idempotency key from the SDK batch. Must be unique across all bot detection events.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".metadata    IS 'Detection detail bag: detection_type, signals, automation_score, confidence, model version.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".created_by  IS 'UUID of the detection service that wrote this row.';
COMMENT ON COLUMN "10_kbio"."62_evt_bot_detection_events".created_at  IS 'Row creation timestamp (UTC).';

GRANT SELECT            ON "10_kbio"."62_evt_bot_detection_events" TO tennetctl_read;
GRANT SELECT, INSERT    ON "10_kbio"."62_evt_bot_detection_events" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- 63_evt_device_fingerprint_events — Device fingerprint snapshots
-- ---------------------------------------------------------------------------
CREATE TABLE "10_kbio"."63_evt_device_fingerprint_events" (
    id          VARCHAR(36)   NOT NULL,
    device_id   VARCHAR(36)   NOT NULL,
    session_id  VARCHAR(36)   NOT NULL,
    user_hash   VARCHAR(64),
    metadata    JSONB,
    created_by  VARCHAR(36)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_kbio_evt_device_fingerprint_events        PRIMARY KEY (id),
    CONSTRAINT fk_kbio_evt_device_fingerprint_events_device FOREIGN KEY (device_id)
                                                             REFERENCES "10_kbio"."11_fct_devices" (id)
);

CREATE INDEX idx_kbio_evt_device_fingerprint_events_device_created  ON "10_kbio"."63_evt_device_fingerprint_events" (device_id, created_at DESC);
CREATE INDEX idx_kbio_evt_device_fingerprint_events_session_created ON "10_kbio"."63_evt_device_fingerprint_events" (session_id, created_at DESC);
CREATE INDEX idx_kbio_evt_device_fingerprint_events_user_created    ON "10_kbio"."63_evt_device_fingerprint_events" (user_hash, created_at DESC);

COMMENT ON TABLE  "10_kbio"."63_evt_device_fingerprint_events" IS
    'Append-only log of device fingerprint snapshots. One row per fingerprinting pass, '
    'capturing the full signal state at that moment in time. Used for drift detection '
    'and replay analysis. No updated_at, no deleted_at.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".id          IS 'UUID v7 primary key.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".device_id   IS 'FK → 11_fct_devices. The device being fingerprinted.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".session_id  IS 'The session during which this fingerprint was captured. Not a FK — hot ingest path.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".user_hash   IS 'Pseudonymous user identifier at capture time. NULL if user was not yet identified.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".metadata    IS 'Fingerprint detail bag: tier1_hash, tier2_hash, tier3_hash, match_score, automation_signals, canvas, webgl, audio fingerprints.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".created_by  IS 'UUID of the fingerprinting service that wrote this row.';
COMMENT ON COLUMN "10_kbio"."63_evt_device_fingerprint_events".created_at  IS 'Row creation timestamp (UTC).';

GRANT SELECT            ON "10_kbio"."63_evt_device_fingerprint_events" TO tennetctl_read;
GRANT SELECT, INSERT    ON "10_kbio"."63_evt_device_fingerprint_events" TO tennetctl_write;

-- DOWN =======================================================================

-- Drop event tables first (no dependencies)
DROP TABLE IF EXISTS "10_kbio"."63_evt_device_fingerprint_events";
DROP TABLE IF EXISTS "10_kbio"."62_evt_bot_detection_events";
DROP TABLE IF EXISTS "10_kbio"."61_evt_anomaly_events";
DROP TABLE IF EXISTS "10_kbio"."60_evt_score_events";

-- Drop link tables next
DROP TABLE IF EXISTS "10_kbio"."41_lnk_session_devices";
DROP TABLE IF EXISTS "10_kbio"."40_lnk_user_devices";

-- Drop detail tables
DROP TABLE IF EXISTS "10_kbio"."20_dtl_attrs";

-- Drop fact tables (in reverse dependency order: dependents before dependencies)
DROP TABLE IF EXISTS "10_kbio"."15_fct_predefined_policies";
DROP TABLE IF EXISTS "10_kbio"."14_fct_challenges";
DROP TABLE IF EXISTS "10_kbio"."13_fct_trusted_entities";
DROP TABLE IF EXISTS "10_kbio"."12_fct_user_profiles";
DROP TABLE IF EXISTS "10_kbio"."11_fct_devices";
DROP TABLE IF EXISTS "10_kbio"."10_fct_sessions";
