-- =============================================================================
-- Signal AI Engineering Pipeline
-- Adds: signal spec sessions, agent type codes, ai_generated_tests dataset source
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. New dataset source dimension for AI-generated test datasets
-- ---------------------------------------------------------------------------
INSERT INTO "15_sandbox"."05_dim_dataset_sources" (code, name, description)
VALUES (
    'ai_generated_tests',
    'AI-Generated Test Dataset',
    'Test dataset auto-generated by the Signal Spec Pipeline — shape-preserving, structurally identical to live system data'
)
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. New agent type codes for the signal pipeline
-- ---------------------------------------------------------------------------
INSERT INTO "20_ai"."02_dim_agent_types" (code, name, description) VALUES
    ('signal_generate',  'Signal Code Generator (Quick)',    'Quick-generate mode: prompt → compile → test → fix loop'),
    ('signal_spec',      'Signal Specification Agent',       'Interactive spec generation with feasibility gate via SSE streaming'),
    ('test_dataset_gen', 'Test Dataset Generator',           'Shape-preserving AI test dataset generation from signal spec'),
    ('signal_codegen',   'Signal Code Generator (Spec-Driven)', 'Spec-driven iterative Python code generation + args schema'),
    ('threat_composer',  'Threat Type Composer',             'Semantic threat type composition from validated signals'),
    ('library_builder',  'Control Library Builder',          'Creates policies and control test libraries from threat types')
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Signal spec sessions table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "20_ai"."46_fct_signal_spec_sessions" (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_key           TEXT NOT NULL,
    user_id              UUID NOT NULL,
    org_id               UUID,
    workspace_id         UUID,
    signal_id            UUID,
    connector_type_code  TEXT,
    source_dataset_id    UUID,
    status               TEXT NOT NULL DEFAULT 'drafting'
                             CHECK (status IN ('drafting', 'feasibility_checking', 'feasible',
                                               'partial', 'infeasible', 'approved', 'pipeline_running',
                                               'pipeline_complete', 'pipeline_failed')),
    current_spec         JSONB,
    feasibility_result   JSONB,
    -- Rolling window: only last 20 turns stored (enforced in service layer)
    conversation_history JSONB NOT NULL DEFAULT '[]',
    job_id               UUID,
    error_message        TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signal_spec_sessions_user
    ON "20_ai"."46_fct_signal_spec_sessions" (tenant_key, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_signal_spec_sessions_signal
    ON "20_ai"."46_fct_signal_spec_sessions" (signal_id)
    WHERE signal_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_signal_spec_sessions_status
    ON "20_ai"."46_fct_signal_spec_sessions" (tenant_key, status, updated_at DESC);
