"use client"

import { useEffect, useState } from "react"
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Input,
  Label,
} from "@kcontrol/ui"
import {
  AlertCircle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  Edit3,
  Loader2,
  Plus,
  Save,
  Send,
  Trash2,
  FileText,
  ArrowRight,
  Pencil,
  X,
} from "lucide-react"
import {
  createQuestionnaire,
  fetchQuestionnaireVersion,
  listQuestionnaires,
  publishQuestionnaireVersion,
  upsertQuestionnaireAssignment,
  updateQuestionnaireVersionContent,
  setSectionActiveStatus,
  setQuestionActiveStatus,
  updateQuestionnaire,
  deleteQuestionnaire,
} from "@/lib/api/questionnaires"
import type {
  CreateQuestionnaireRequest,
  QuestionnaireContentSchema,
  QuestionnaireResponse,
  QuestionOptionSchema,
  QuestionSchema,
  SectionSchema,
} from "@/lib/types/questionnaires"
import { listOrgs } from "@/lib/api/orgs"
import { listWorkspaces } from "@/lib/api/workspaces"
import type { OrgResponse, WorkspaceResponse } from "@/lib/types/orgs"

// Helpers
// IDs are now exclusively generated by the backend.

function blankQuestion(): QuestionSchema {
  return {
    id: null as any, // assigned by backend
    label: "",
    type: "single",
    required: false,
    options: [{ value: null as any, label: "Option 1" }],
    helperText: null,
    placeholder: null,
    subsection: null,
    is_active: true,
  }
}

function blankSection(): SectionSchema {
  return {
    id: null as any, // assigned by backend
    title: "",
    description: null,
    icon: null,
    is_active: true,
    questions: [blankQuestion()],
  }
}

// ─── Option Editor ────────────────────────────────────────────────────────────
function OptionsEditor({
  options,
  onChange,
}: {
  options: QuestionOptionSchema[]
  onChange: (opts: QuestionOptionSchema[]) => void
}) {
  function updateOption(idx: number, field: keyof QuestionOptionSchema, val: string) {
    const copy = [...options]
    copy[idx] = { ...copy[idx], [field]: val }
    onChange(copy)
  }
  function addOption() {
    onChange([...options, { value: null as any, label: `Option ${options.length + 1}` }])
  }
  function removeOption(idx: number) {
    onChange(options.filter((_, i) => i !== idx))
  }

  return (
    <div className="space-y-2">
      {options.map((opt, idx) => (
        <div key={idx} className="flex gap-2 items-center">
          <Input
            placeholder="Option Label"
            value={opt.label}
            onChange={(e) => updateOption(idx, "label", e.target.value)}
            className="h-8 flex-1 text-xs"
          />
          <button
            type="button"
            onClick={() => removeOption(idx)}
            className="h-8 w-8 flex items-center justify-center rounded-md text-muted-foreground hover:text-red-500 hover:bg-red-500/10 transition-colors"
          >
            <Trash2 className="h-4 w-4" />
          </button>
        </div>
      ))}
      <button
        type="button"
        onClick={addOption}
        className="text-xs text-primary flex items-center gap-2 hover:underline"
      >
        <Plus className="h-3 w-3" />
        Add Option
      </button>
    </div>
  )
}

// ─── Question Editor ──────────────────────────────────────────────────────────
function QuestionEditor({
  question,
  index,
  onChange,
  onRemove,
  onToggleActive,
  onDelete,
}: {
  question: QuestionSchema
  index: number
  onChange: (q: QuestionSchema) => void
  onRemove: () => void
  onToggleActive: (active: boolean) => void
  onDelete?: () => void
}) {
  const [expanded, setExpanded] = useState(true)
  const [localEditing, setLocalEditing] = useState(!question.id)
  const needsOptions = question.type === "single" || question.type === "multi"

  return (
    <div className={`rounded-lg border bg-card ${localEditing ? 'ring-1 ring-primary' : ''}`}>
      <div className="flex items-center justify-between px-4 py-3 border-b bg-muted/20">
        <button
          type="button"
          className="flex-1 flex items-center gap-3 text-sm font-medium text-left"
          onClick={() => {
            if (!localEditing) setExpanded((e) => !e)
          }}
        >
          <div className={`h-6 w-6 rounded-full flex items-center justify-center text-xs font-semibold ${
            localEditing ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
          }`}>
            {index + 1}
          </div>
          <span className={question.label ? "text-foreground" : "text-muted-foreground italic"}>
            {question.label || "Untitled Question"}
          </span>
        </button>
        <div className="flex items-center gap-2">
          {onDelete && (
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                onDelete();
              }}
              className="p-1.5 rounded text-muted-foreground hover:text-red-500 hover:bg-red-500/10 transition-colors"
              title="Delete question"
            >
              <X className="h-4 w-4" />
            </button>
          )}
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onToggleActive(question.is_active === false);
            }}
            className={`flex items-center gap-1.5 px-2 py-1 rounded text-xs ${
              question.is_active !== false
                ? 'bg-green-500/10 text-green-600' 
                : 'bg-red-500/10 text-red-500'
            }`}
          >
            {question.is_active !== false ? <CheckCircle2 className="h-3 w-3" /> : <AlertCircle className="h-3 w-3" />}
            {question.is_active !== false ? 'Active' : 'Inactive'}
          </button>
          <button
            type="button"
            onClick={() => {
              setLocalEditing(!localEditing)
              if (!expanded) setExpanded(true)
            }}
            className={`flex items-center gap-1.5 px-2 py-1 rounded text-xs ${
              localEditing 
                ? 'bg-primary text-primary-foreground' 
                : 'bg-muted text-muted-foreground hover:bg-muted/80'
            }`}
          >
            {localEditing ? <CheckCircle2 className="h-3 w-3" /> : <Edit3 className="h-3 w-3" />}
            {localEditing ? 'Done' : 'Edit'}
          </button>
          {!localEditing && (
            <button
              type="button"
              onClick={() => setExpanded((e) => !e)}
              className="p-1 text-muted-foreground hover:text-foreground"
            >
              {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
            </button>
          )}
        </div>
      </div>

      {expanded && (
        <div className="p-4 space-y-4">
          {localEditing ? (
            <div className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label className="text-xs">Question Label</Label>
                  <Input
                    value={question.label}
                    onChange={(e) => onChange({ ...question, label: e.target.value })}
                    placeholder="e.g. What is your primary industry?"
                    className="h-9 text-sm"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Answer Type</Label>
                  <select
                    value={question.type}
                    onChange={(e) => onChange({ ...question, type: e.target.value as QuestionSchema["type"], options: e.target.value !== "text" ? (question.options ?? [{ value: null as any, label: "Option 1" }]) : null })}
                    className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                  >
                    <option value="single">Single Choice</option>
                    <option value="multi">Multi Choice</option>
                    <option value="text">Free Text</option>
                  </select>
                </div>
              </div>

              <div className="space-y-1.5">
                <Label className="text-xs">Helper Text (optional)</Label>
                <Input
                  value={question.helperText ?? ""}
                  onChange={(e) => onChange({ ...question, helperText: e.target.value || null })}
                  placeholder="e.g. Select all that apply"
                  className="h-9 text-sm"
                />
              </div>

              {needsOptions && (
                <div className="space-y-2 p-3 rounded-md bg-muted/30 border">
                  <Label className="text-xs">Options</Label>
                  <OptionsEditor
                    options={question.options ?? []}
                    onChange={(opts) => onChange({ ...question, options: opts })}
                  />
                </div>
              )}

              <div className="flex items-center justify-between pt-2 border-t">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={question.required}
                    onChange={(e) => onChange({ ...question, required: e.target.checked })}
                    className="h-4 w-4 rounded"
                  />
                  <span className="text-xs text-muted-foreground">Required Question</span>
                </label>
                <button
                  type="button"
                  onClick={onRemove}
                  className="px-2 py-1 rounded text-xs text-red-500 hover:bg-red-500/10 flex items-center gap-1"
                >
                  <Trash2 className="h-3 w-3" /> Remove
                </button>
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              {question.helperText && (
                <p className="text-xs text-muted-foreground">{question.helperText}</p>
              )}
              {needsOptions ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                  {question.options?.slice(0, 4).map((opt, i) => (
                    <div key={i} className="text-xs bg-muted/30 px-3 py-2 rounded flex items-center gap-2">
                      <div className="h-1.5 w-1.5 rounded-full bg-primary/40" />
                      {opt.label}
                    </div>
                  ))}
                  {(question.options?.length ?? 0) > 4 && (
                    <div className="text-xs text-primary font-medium px-3 py-2">
                      + {(question.options?.length ?? 0) - 4} more
                    </div>
                  )}
                </div>
              ) : (
                <div className="h-10 bg-muted/20 rounded flex items-center px-3 border border-dashed border-border">
                  <span className="text-xs text-muted-foreground">Free text response</span>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ─── Section Builder ──────────────────────────────────────────────────────────
function SectionBuilder({
  section,
  index,
  onChange,
  onRemove,
  onToggleActive,
  onQuestionToggle,
}: {
  section: SectionSchema
  index: number
  onChange: (s: SectionSchema) => void
  onRemove: () => void
  onToggleActive: (active: boolean) => void
  onQuestionToggle?: (qIdx: number, active: boolean) => void
}) {
  const [expanded, setExpanded] = useState(index === 0 || !section.id)

  function updateQuestion(qIdx: number, q: QuestionSchema) {
    const qs = [...section.questions]
    qs[qIdx] = q
    onChange({ ...section, questions: qs })
  }
  function removeQuestion(qIdx: number) {
    onChange({ ...section, questions: section.questions.filter((_, i) => i !== qIdx) })
  }
  function addQuestion() {
    onChange({ ...section, questions: [...section.questions, blankQuestion()] })
  }

  return (
    <div className={`rounded-lg border bg-card ${expanded ? 'ring-1 ring-primary/30' : ''}`}>
      <div 
        className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-muted/30"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-3">
          <div className={`h-8 w-8 rounded-md flex items-center justify-center text-sm font-semibold ${
            expanded ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
          }`}>
            {index + 1}
          </div>
          <div>
            <h4 className="text-sm font-semibold">
              {section.title || <span className="italic text-muted-foreground">Untitled Section</span>}
            </h4>
            <p className="text-xs text-muted-foreground">{section.questions.length} questions</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onToggleActive(section.is_active === false);
            }}
            className={`flex items-center gap-1.5 px-2 py-1 rounded text-xs ${
              section.is_active !== false
                ? 'bg-green-500/10 text-green-600' 
                : 'bg-red-500/10 text-red-500'
            }`}
          >
            {section.is_active !== false ? <CheckCircle2 className="h-3 w-3" /> : <AlertCircle className="h-3 w-3" />}
            {section.is_active !== false ? 'Active' : 'Inactive'}
          </button>
          <button
            type="button"
            onClick={(e) => { e.stopPropagation(); onRemove() }}
            className="p-1.5 rounded text-muted-foreground hover:text-red-500 hover:bg-red-500/10"
          >
            <Trash2 className="h-4 w-4" />
          </button>
          <ChevronDown className={`h-4 w-4 text-muted-foreground transition-transform ${expanded ? 'rotate-180' : ''}`} />
        </div>
      </div>

      {expanded && (
        <div className="border-t p-4 space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label className="text-xs">Section Title</Label>
              <Input
                value={section.title}
                onChange={(e) => onChange({ ...section, title: e.target.value })}
                placeholder="e.g. Business Context"
                className="h-9 text-sm"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Description (optional)</Label>
              <Input
                value={section.description ?? ""}
                onChange={(e) => onChange({ ...section, description: e.target.value || null })}
                placeholder="e.g. Tell us about your business"
                className="h-9 text-sm"
              />
            </div>
          </div>

          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h5 className="text-xs font-medium text-muted-foreground">Questions</h5>
              <Badge variant="secondary" className="text-xs">{section.questions.length}</Badge>
            </div>
            
            <div className="space-y-3">
              {section.questions.map((q, qi) => (
                <QuestionEditor
                  key={q.id || `new-q-${qi}`}
                  question={q}
                  index={qi}
                  onChange={(updated) => updateQuestion(qi, updated)}
                  onRemove={() => removeQuestion(qi)}
                  onDelete={() => removeQuestion(qi)}
                  onToggleActive={(active) => {
                    if (onQuestionToggle) {
                      onQuestionToggle(qi, active)
                    } else {
                      updateQuestion(qi, { ...q, is_active: active })
                    }
                  }}
                />
              ))}
            </div>

            <button
              type="button"
              onClick={addQuestion}
              className="w-full rounded-md border border-dashed py-3 text-sm text-primary hover:bg-primary/5 flex items-center justify-center gap-2"
            >
              <Plus className="h-4 w-4" />
              Add Question
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function AdminQuestionnairesPage() {
  const [questionnaires, setQuestionnaires] = useState<QuestionnaireResponse[]>([])
  const [loadingList, setLoadingList] = useState(true)
  const [listError, setListError] = useState<string | null>(null)

  // Create form state
  const [creating, setCreating] = useState(false)
  const [createName, setCreateName] = useState("")
  const [createCode, setCreateCode] = useState("")
  const [createDesc, setCreateDesc] = useState("")
  const [createScope, setCreateScope] = useState<"platform" | "org" | "workspace">("platform")
  const [createSaving, setCreateSaving] = useState(false)
  const [createError, setCreateError] = useState<string | null>(null)
  const [createSuccess, setCreateSuccess] = useState(false)

  // Edit template state
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editName, setEditName] = useState("")
  const [editDesc, setEditDesc] = useState("")
  const [editScope, setEditScope] = useState<"platform" | "org" | "workspace">("platform")
  const [editSaving, setEditSaving] = useState(false)
  const [editError, setEditError] = useState<string | null>(null)

  // Delete confirmation state
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null)
  const [deleteSaving, setDeleteSaving] = useState(false)

  // Builder state
  const [selectedQId, setSelectedQId] = useState<string | null>(null)
  const [builderSections, setBuilderSections] = useState<SectionSchema[]>([blankSection()])
  const [publishing, setPublishing] = useState(false)
  const [publishError, setPublishError] = useState<string | null>(null)
  const [publishSuccess, setPublishSuccess] = useState(false)
  const [syncing, setSyncing] = useState(false)
  const [syncError, setSyncError] = useState<string | null>(null)

  // Assignment state
  const [orgs, setOrgs] = useState<OrgResponse[]>([])
  const [workspaces, setWorkspaces] = useState<WorkspaceResponse[]>([])
  const [assignOrgId, setAssignOrgId] = useState("")
  const [assignWsId, setAssignWsId] = useState("")
  const [assignScope, setAssignScope] = useState<"platform" | "org" | "workspace">("platform")
  const [assigning, setAssigning] = useState(false)
  const [assignError, setAssignError] = useState<string | null>(null)
  const [assignSuccess, setAssignSuccess] = useState(false)

  useEffect(() => {
    listQuestionnaires()
      .then(setQuestionnaires)
      .catch((err) => setListError(err.message))
      .finally(() => setLoadingList(false))
    listOrgs().then(setOrgs).catch(() => [])
  }, [])

  useEffect(() => {
    if (!selectedQId) {
      setBuilderSections([blankSection()])
      return
    }

    const q = questionnaires.find(q => q.id === selectedQId)
    if (!q?.active_version_id) {
      setBuilderSections([blankSection()])
      return
    }

    setPublishError(null)
    setPublishSuccess(false)
    fetchQuestionnaireVersion(q.active_version_id)
      .then(version => {
        setBuilderSections(version.content_jsonb.sections)
      })
      .catch(err => setPublishError(err.message))
  }, [selectedQId, questionnaires])

  useEffect(() => {
    if (!assignOrgId) { setWorkspaces([]); return }
    listWorkspaces(assignOrgId).then(setWorkspaces).catch(() => setWorkspaces([]))
  }, [assignOrgId])

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault()
    if (!createName.trim() || !createCode.trim()) return
    setCreateSaving(true)
    setCreateError(null)
    setCreateSuccess(false)
    try {
      const payload: CreateQuestionnaireRequest = {
        questionnaire_code: createCode.trim(),
        name: createName.trim(),
        description: createDesc.trim() || null,
        intended_scope: createScope,
      }
      const created = await createQuestionnaire(payload)
      setQuestionnaires((prev) => [created, ...prev])
      setCreateSuccess(true)
      setCreateName("")
      setCreateCode("")
      setCreateDesc("")
      setCreating(false)
    } catch (err) {
      setCreateError(err instanceof Error ? err.message : "Failed to create")
    } finally {
      setCreateSaving(false)
    }
  }

  function startEditTemplate(t: QuestionnaireResponse) {
    setEditingId(t.id)
    setEditName(t.name)
    setEditDesc(t.description || "")
    setEditScope(t.intended_scope)
    setEditError(null)
  }

  function cancelEditTemplate() {
    setEditingId(null)
    setEditError(null)
  }

  async function handleEditTemplate(e: React.FormEvent) {
    e.preventDefault()
    if (!editingId || !editName.trim()) return
    setEditSaving(true)
    setEditError(null)
    try {
      const payload: Parameters<typeof updateQuestionnaire>[1] = {
        name: editName.trim(),
        description: editDesc.trim() || null,
        intended_scope: editScope,
      }
      const updated = await updateQuestionnaire(editingId, payload)
      setQuestionnaires((prev) =>
        prev.map((q) => (q.id === editingId ? updated : q))
      )
      setEditingId(null)
    } catch (err) {
      setEditError(err instanceof Error ? err.message : "Failed to update")
    } finally {
      setEditSaving(false)
    }
  }

  function requestDeleteTemplate(id: string) {
    setDeleteConfirm(id)
  }

  function cancelDeleteTemplate() {
    setDeleteConfirm(null)
  }

  async function handleDeleteTemplate() {
    if (!deleteConfirm) return
    setDeleteSaving(true)
    try {
      await deleteQuestionnaire(deleteConfirm)
      setQuestionnaires((prev) => prev.filter((q) => q.id !== deleteConfirm))
      if (selectedQId === deleteConfirm) {
        setSelectedQId(null)
      }
      setDeleteConfirm(null)
    } catch (err) {
      setEditError(err instanceof Error ? err.message : "Failed to delete")
    } finally {
      setDeleteSaving(false)
    }
  }

  async function handlePublish() {
    if (!selectedQId) return
    setPublishing(true)
    setPublishError(null)
    setPublishSuccess(false)
    try {
      const content: QuestionnaireContentSchema = { sections: builderSections }
      const version = await publishQuestionnaireVersion(selectedQId, content)
      setPublishSuccess(true)
      setBuilderSections(version.content_jsonb.sections) // Sync IDs from backend
      const updated = await listQuestionnaires()
      setQuestionnaires(updated)
    } catch (err) {
      setPublishError(err instanceof Error ? err.message : "Failed to publish")
    } finally {
      setPublishing(false)
    }
  }

  async function handleUpdateVersion() {
    if (!selectedQ?.active_version_id) return
    
    setSyncing(true)
    setSyncError(null)
    setPublishSuccess(false)
    try {
      const content: QuestionnaireContentSchema = { sections: builderSections }
      const result = await updateQuestionnaireVersionContent(selectedQ.active_version_id, content)
      setBuilderSections(result.content_jsonb.sections) // Sync IDs from backend
      setPublishSuccess(true) // Visual feedback
    } catch (err) {
      setSyncError(err instanceof Error ? err.message : "Failed to update version")
    } finally {
      setSyncing(false)
    }
  }

  async function handleAssign(e: React.FormEvent) {
    e.preventDefault()
    if (!selectedQ?.active_version_id) return
    setAssigning(true)
    setAssignError(null)
    setAssignSuccess(false)
    try {
      await upsertQuestionnaireAssignment({
        assignment_scope: assignScope,
        org_id: assignOrgId || null,
        workspace_id: assignWsId || null,
        questionnaire_version_id: selectedQ.active_version_id,
      })
      setAssignSuccess(true)
    } catch (err) {
      setAssignError(err instanceof Error ? err.message : "Failed to assign")
    } finally {
      setAssigning(false)
    }
  }

  const selectedQ = questionnaires.find((q) => q.id === selectedQId)

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-20 px-4">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <FileText className="h-4 w-4" />
            <span>Admin</span>
            <ArrowRight className="h-3 w-3" />
            <span>Questionnaires</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight">Risk Questionnaires</h1>
          <p className="text-sm text-muted-foreground">
            Create and manage questionnaire templates, publish versions, and assign to organizations.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Template List */}
        <div className="space-y-4">
          <Card>
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base">Templates</CardTitle>
                <Button size="sm" variant="outline" onClick={() => setCreating((c) => !c)}>
                  <Plus className="h-4 w-4 mr-1" /> New
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-2">
              {creating && (
                <form onSubmit={handleCreate} className="rounded-lg border p-4 space-y-3 mb-4">
                    <div className="space-y-2">
                      <div className="space-y-1">
                        <Label className="text-xs">Name</Label>
                        <Input
                          value={createName}
                          onChange={(e) => setCreateName(e.target.value)}
                          placeholder="Standard Risk Assessment"
                          className="h-8 text-sm"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs">Description</Label>
                        <Input
                          value={createDesc}
                          onChange={(e) => setCreateDesc(e.target.value)}
                          placeholder="Assess organizational risk posture..."
                          className="h-8 text-sm"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs">Code</Label>
                        <Input
                          value={createCode}
                          onChange={(e) => setCreateCode(e.target.value)}
                          placeholder="global-risk-v1"
                          className="h-8 text-sm font-mono"
                        />
                      </div>
                    <div className="space-y-1">
                      <Label className="text-xs">Scope</Label>
                      <select
                        value={createScope}
                        onChange={(e) => setCreateScope(e.target.value as typeof createScope)}
                        className="w-full h-8 rounded-md border border-input bg-background px-2 text-sm"
                      >
                        <option value="platform">Platform (Global)</option>
                        <option value="org">Organization</option>
                        <option value="workspace">Workspace</option>
                      </select>
                    </div>
                  </div>

                  {createError && (
                    <p className="text-xs text-red-500">{createError}</p>
                  )}
                  {createSuccess && <p className="text-xs text-green-600">Created successfully!</p>}
                  
                  <div className="flex gap-2">
                    <Button type="submit" size="sm" disabled={createSaving} className="flex-1">
                      {createSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Create"}
                    </Button>
                    <Button type="button" variant="ghost" size="sm" onClick={() => setCreating(false)}>Cancel</Button>
                  </div>
                </form>
              )}

              {loadingList ? (
                <div className="space-y-2">
                  {[...Array(3)].map((_, i) => <div key={i} className="h-12 rounded-md bg-muted animate-pulse" />)}
                </div>
              ) : listError ? (
                <p className="text-xs text-red-500">{listError}</p>
              ) : questionnaires.length === 0 ? (
                <div className="text-center py-8">
                  <ClipboardList className="h-8 w-8 text-muted-foreground/30 mx-auto mb-2" />
                  <p className="text-xs text-muted-foreground">No questionnaires yet.</p>
                </div>
              ) : (
                <>
                  {questionnaires.map((t) => {
                    const isActive = selectedQId === t.id
                    const isEditing = editingId === t.id
                    const isDeleteConfirm = deleteConfirm === t.id

                    if (isDeleteConfirm) {
                      return (
                        <div
                          key={t.id}
                          className="rounded-lg border border-red-300 bg-red-50/50 p-4 space-y-3"
                        >
                          <p className="text-sm font-medium text-red-700">Delete "{t.name}"?</p>
                          <p className="text-xs text-red-600">
                            All versions, questions, and assignments will be permanently removed.
                          </p>
                          <div className="flex gap-2">
                            <Button
                              size="sm"
                              variant="destructive"
                              onClick={handleDeleteTemplate}
                              disabled={deleteSaving}
                              className="flex-1"
                            >
                              {deleteSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Delete"}
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={cancelDeleteTemplate}
                              disabled={deleteSaving}
                            >
                              Cancel
                            </Button>
                          </div>
                        </div>
                      )
                    }

                    if (isEditing) {
                      return (
                        <form
                          key={t.id}
                          onSubmit={handleEditTemplate}
                          className="rounded-lg border border-primary bg-primary/5 p-4 space-y-3"
                        >
                          <div className="space-y-2">
                            <div className="space-y-1">
                              <Label className="text-xs">Name</Label>
                              <Input
                                value={editName}
                                onChange={(e) => setEditName(e.target.value)}
                                placeholder="Standard Risk Assessment"
                                className="h-8 text-sm"
                              />
                            </div>
                            <div className="space-y-1">
                              <Label className="text-xs">Scope</Label>
                              <select
                                value={editScope}
                                onChange={(e) => setEditScope(e.target.value as typeof editScope)}
                                className="w-full h-8 rounded-md border border-input bg-background px-2 text-sm"
                              >
                                <option value="platform">Platform (Global)</option>
                                <option value="org">Organization</option>
                                <option value="workspace">Workspace</option>
                              </select>
                            </div>
                          </div>

                          {editError && (
                            <p className="text-xs text-red-500">{editError}</p>
                          )}

                          <div className="flex gap-2">
                            <Button type="submit" size="sm" disabled={editSaving} className="flex-1">
                              {editSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save"}
                            </Button>
                            <Button type="button" variant="ghost" size="sm" onClick={cancelEditTemplate}>
                              Cancel
                            </Button>
                          </div>
                        </form>
                      )
                    }

                    return (
                      <div
                        key={t.id}
                        className={`rounded-lg border p-3 transition-all ${
                          isActive
                            ? "border-primary bg-primary/5"
                            : "border-border hover:border-primary/50"
                        }`}
                      >
                        <button
                          onClick={() => { setSelectedQId(t.id); setPublishSuccess(false) }}
                          className="w-full text-left"
                        >
                          <div className="flex items-start justify-between gap-2 mb-1">
                            <div className={`h-8 w-8 rounded-md flex items-center justify-center ${
                              isActive ? 'bg-primary/20 text-primary' : 'bg-muted text-muted-foreground'
                            }`}>
                              <ClipboardList className="h-4 w-4" />
                            </div>
                            <div className="flex flex-col items-end gap-1">
                              <Badge variant={isActive ? "default" : "secondary"} className="text-xs">
                                v{t.latest_version_number ?? '1.0'}
                              </Badge>
                              <Badge variant="outline" className="text-xs">{t.intended_scope}</Badge>
                            </div>
                          </div>
                          <p className="text-sm font-medium truncate">{t.name}</p>
                          {t.description && (
                            <p
                              className="text-xs text-muted-foreground overflow-hidden text-ellipsis cursor-help"
                              style={{
                                display: '-webkit-box',
                                WebkitLineClamp: 2,
                                WebkitBoxOrient: 'vertical',
                              }}
                              title={t.description}
                            >
                              {t.description}
                            </p>
                          )}
                          <p className="text-xs text-muted-foreground">{t.current_status}</p>
                        </button>
                        <div className="flex items-center gap-1 mt-2 pt-2 border-t">
                          <button
                            type="button"
                            onClick={(e) => { e.stopPropagation(); startEditTemplate(t) }}
                            className="flex items-center gap-1 px-2 py-1 rounded text-xs text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors"
                          >
                            <Pencil className="h-3 w-3" /> Edit
                          </button>
                          <button
                            type="button"
                            onClick={(e) => { e.stopPropagation(); requestDeleteTemplate(t.id) }}
                            className="flex items-center gap-1 px-2 py-1 rounded text-xs text-muted-foreground hover:text-red-500 hover:bg-red-500/10 transition-colors"
                          >
                            <Trash2 className="h-3 w-3" /> Delete
                          </button>
                        </div>
                      </div>
                    )
                  })}
                </>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Right: Builder + Assignment */}
        <div className="lg:col-span-2 space-y-6">
          {selectedQ ? (
            <>
              {/* Question Builder */}
              <Card>
                <CardHeader className="pb-4">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div className="space-y-1">
                      <CardTitle className="text-lg">{selectedQ.name}</CardTitle>
                      <CardDescription>Build and publish a new version of this questionnaire.</CardDescription>
                    </div>
                    <div className="flex flex-col sm:flex-row sm:items-center gap-2">
                        <Button
                          variant="outline"
                          onClick={handleUpdateVersion}
                          disabled={syncing || !selectedQ?.active_version_id}
                          className="w-full sm:w-auto"
                        >
                          {syncing ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}
                          {syncing ? "Updating…" : "Update Current Version"}
                        </Button>
                        <Button
                          onClick={handlePublish}
                          disabled={publishing}
                          className="w-full sm:w-auto"
                        >
                          {publishing ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Send className="h-4 w-4 mr-2" />}
                          {publishing ? "Publishing…" : "Publish New Version"}
                        </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-4">
                    {builderSections.map((sec, si) => (
                      <SectionBuilder
                        key={sec.id || `new-sec-${si}`}
                        section={sec}
                        index={si}
                        onChange={(updatedSection) => {
                          const nextSections = [...builderSections]
                          nextSections[si] = updatedSection
                          setBuilderSections(nextSections)
                        }}
                        onRemove={() => setBuilderSections(builderSections.filter((_, i) => i !== si))}
                        onToggleActive={async (active) => {
                          if (!selectedQ?.active_version_id || !sec.id) return
                          setSyncing(true)
                          setSyncError(null)
                          try {
                            const result = await setSectionActiveStatus(selectedQ.active_version_id, sec.id, active)
                            setBuilderSections(result.content_jsonb.sections)
                          } catch (err) {
                            setSyncError(err instanceof Error ? err.message : "Failed to update section status")
                          } finally {
                            setSyncing(false)
                          }
                        }}
                        onQuestionToggle={async (qIdx, active) => {
                          const question = builderSections[si].questions[qIdx]
                          // Only call API if question has an ID (was saved to backend)
                          if (!selectedQ?.active_version_id || !sec.id || !question?.id) {
                            // For new questions without ID, just update local state
                            const nextSections = [...builderSections]
                            const nextQuestions = [...nextSections[si].questions]
                            nextQuestions[qIdx] = { ...nextQuestions[qIdx], is_active: active }
                            nextSections[si] = { ...nextSections[si], questions: nextQuestions }
                            setBuilderSections(nextSections)
                            return
                          }
                          setSyncing(true)
                          setSyncError(null)
                          try {
                            const result = await setQuestionActiveStatus(selectedQ.active_version_id, sec.id, question.id, active)
                            setBuilderSections(result.content_jsonb.sections)
                          } catch (err) {
                            setSyncError(err instanceof Error ? err.message : "Failed to update question status")
                          } finally {
                            setSyncing(false)
                          }
                        }}
                      />
                    ))}
                  </div>

                  <button
                    type="button"
                    onClick={() => setBuilderSections([...builderSections, blankSection()])}
                    className="w-full rounded-md border border-dashed py-3 text-sm text-primary hover:bg-primary/5 flex items-center justify-center gap-2"
                  >
                    <Plus className="h-4 w-4" />
                    Add New Section
                  </button>

                  {publishError && (
                    <div className="flex items-center gap-2 rounded-md border border-red-200 bg-red-50 px-4 py-3 dark:border-red-800 dark:bg-red-950">
                      <AlertCircle className="h-4 w-4 text-red-500" />
                      <p className="text-sm text-red-600">{publishError}</p>
                    </div>
                  )}
                  {publishSuccess && (
                    <div className="flex items-center gap-2 rounded-md border border-green-200 bg-green-50 px-4 py-3 dark:border-green-800 dark:bg-green-950">
                      <CheckCircle2 className="h-4 w-4 text-green-600" />
                      <p className="text-sm text-green-700">New version published successfully!</p>
                    </div>
                  )}
                  {syncing && (
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <Loader2 className="h-3 w-3 animate-spin" />
                      Syncing changes...
                    </div>
                  )}
                  {syncError && (
                    <div className="flex items-center gap-2 text-xs text-red-500">
                      <AlertCircle className="h-3 w-3" />
                      {syncError}
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Assignment Panel */}
              <Card>
                <CardHeader className="pb-4">
                  <CardTitle className="text-lg">Assign Version</CardTitle>
                  <CardDescription>Assign the current version to a specific scope or organization.</CardDescription>
                </CardHeader>
                <CardContent>
                  <form onSubmit={handleAssign} className="space-y-4">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      <div className="space-y-1.5">
                        <Label className="text-xs">Current Version</Label>
                        <div className="h-9 rounded-md border border-input bg-muted/30 px-3 flex items-center gap-2">
                          <Badge variant="outline" className="text-xs">
                            v{selectedQ?.latest_version_number ?? '1.0'}
                          </Badge>
                          <span className="text-xs text-muted-foreground">
                            {selectedQ?.active_version_id ? 'Ready to assign' : 'Not published yet'}
                          </span>
                        </div>
                      </div>
                      <div className="space-y-1.5">
                        <Label className="text-xs">Target Scope</Label>
                        <select
                          value={assignScope}
                          onChange={(e) => setAssignScope(e.target.value as typeof assignScope)}
                          className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                        >
                          <option value="platform">Platform (Global Default)</option>
                          <option value="org">Organization</option>
                          <option value="workspace">Workspace</option>
                        </select>
                      </div>
                    </div>

                    {(assignScope === "org" || assignScope === "workspace") && (
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div className="space-y-1.5">
                          <Label className="text-xs">Target Organization</Label>
                          <select
                            value={assignOrgId}
                            onChange={(e) => setAssignOrgId(e.target.value)}
                            className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                          >
                            <option value="">— Select org —</option>
                            {orgs.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}
                          </select>
                        </div>
                        {assignScope === "workspace" && (
                          <div className="space-y-1.5">
                            <Label className="text-xs">Target Workspace</Label>
                            <select
                              value={assignWsId}
                              onChange={(e) => setAssignWsId(e.target.value)}
                              className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                            >
                              <option value="">— Select workspace —</option>
                              {workspaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}
                            </select>
                          </div>
                        )}
                      </div>
                    )}

                    {assignError && (
                      <div className="flex items-center gap-2 rounded-md border border-red-200 bg-red-50 px-4 py-3 dark:border-red-800 dark:bg-red-950">
                        <AlertCircle className="h-4 w-4 text-red-500" />
                        <p className="text-sm text-red-600">{assignError}</p>
                      </div>
                    )}
                    {assignSuccess && (
                      <div className="flex items-center gap-2 rounded-md border border-green-200 bg-green-50 px-4 py-3 dark:border-green-800 dark:bg-green-950">
                        <CheckCircle2 className="h-4 w-4 text-green-600" />
                        <p className="text-sm text-green-700">Assignment saved successfully!</p>
                      </div>
                    )}

                    <Button
                      type="submit"
                      disabled={assigning || !selectedQ?.active_version_id}
                    >
                      {assigning ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}
                      {assigning ? "Saving..." : "Save Assignment"}
                    </Button>
                  </form>
                </CardContent>
              </Card>
            </>
          ) : (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-16 text-center">
                <div className="h-14 w-14 rounded-full bg-muted flex items-center justify-center mb-4">
                  <ClipboardList className="h-7 w-7 text-muted-foreground" />
                </div>
                <h3 className="text-lg font-semibold mb-2">No Questionnaire Selected</h3>
                <p className="text-sm text-muted-foreground max-w-md">
                  Select a template from the list to begin building and managing questions.
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  )
}
